// The chat's words (the chat.* namespace of the app's one dictionary, #1408 §4), in English and zh-TW.
import { register } from "/assets/app-i18n.js";

register("chat", {
  en: {
    cmdConfirm: "Clear", cmdRunning: "Running /{0}…", cmdNotCommand: "Not a command here — Enter sends it as a message.", cmdDismiss: "Dismiss", cmdCommands: "Commands",
    cmdChoose: "Choose", cmdCurrent: "current", chipCompact: "Compact", chipClear: "Clear…", chipContext: "Context {0}% used",
    chipModel: "Model: {0} — choose another", chipEffort: "Effort: {0} — choose another",
    cmd_ctx: "Context use, model and effort", cmd_compact: "Compact the conversation", cmd_clear: "Clear the conversation (asks first)",
    cmd_model: "Show or switch the model", cmd_effort: "Show or set the reasoning effort", cmd_cancel: "Stop the current reply",
    cmd_btw: "A side question that does not interrupt", cmd_steer: "Send into the current turn", cmd_pause: "Pause the instance",
    cmd_wake: "Wake a paused instance", cmd_save: "Save the conversation to a file",
    tourTitle: "Welcome to web chat", tourStep: "{0} of {1}", tourBack: "Back", tourNext: "Next", tourDone: "Got it", tourSkip: "Skip",
    tour1: "Pick an instance in the list to chat with it. On a phone, ☰ opens the list.",
    tour2: "It is the same conversation as its Telegram or Discord chat: what you send here shows up there too, and the agent's replies show up in both.",
    tour3: "Attach files and images with 📎, or paste or drop them on the chat.",
    tour4: "While the agent works, Stop reply appears in the message box: it interrupts the current reply. The instance itself keeps running.",
    tour5: "A “needs you” badge means the agent is waiting on its terminal, for example a permission question. Answer it from the buttons in its chat.",
    a11yWorking: "{0} started working", a11yIdle: "{0} finished", a11yReplied: "{0} replied", conversationWith: "Conversation with {0}",
    stopping: "Stopping {0}…", awaiting: "{0} is waiting for your input", approxNote: "Read from the terminal, so approximate", elapsedTitle: "Time since this page saw it start (approximate)",
    dropHere: "Drop files to attach them", asText: "As text", pasteAttached: "A long paste ({0} characters) was attached as a text file", pasteKeptAsText: "No room for another attachment: the long paste stays as text",
    send: "Send", composerPlaceholder: "Message {0}…", composerHint: "Enter to send · Shift+Enter for a new line · / for commands · Esc stops the reply", attachTitle: "Attach files (images, PDF, text — or paste / drop them)",
    pvPreview: "Preview", pvStop: "Stop", pvDownload: "Download", pvMenu: "Preview options", pvHtml: "HTML",
    pvAllowButton: "Allow previews", pvAllow: "Allow HTML previews on this device — they may be able to send data out", pvDisallow: "Stop allowing HTML previews on this device",
    pvConfirm: "Allow HTML previews on this device?\n\nA preview runs the agent's HTML in an isolated frame. It cannot use your login, but it may be able to send data out, and it can slow or freeze this tab. You still click Preview each time.",
    pvNever: "Never preview HTML on this device", pvNeverUndo: "Let this device preview HTML again", pvStarting: "Starting the preview…",
    pvChanged: "Preview stopped — the message changed. Preview again.", pvTruncated: "Truncated — ask the agent to send it as a .html file.",
    pvLoading: "Reading the file…", pvAttOver: "This file is over 1 MiB; it is not previewed.",
    pvAttGone: "This file is no longer available here (it changed, or the fleet restarted). Ask the agent to send it again.",
    pvAttFailed: "Could not read this file. Try again.",
    rbGroup: "Choices", rbChosen: "Chosen by {0}", rbExpired: "Expired — reply in text",
    pvOpenPanel: "Open in panel", pvInPanel: "Shown in the panel.", pvPanel: "HTML preview", pvSource: "From {0}, {1} — show the message",
    pvPage: "Page", pvCode: "Code", pvReload: "Reload", pvClose: "Close the panel", pvBack: "Back to the chat", pvResize: "Resize the preview panel",
    pvNewer: "A newer version is in the reply from {0}.", pvNewerShow: "Show it", pvPanelIdle: "Click Preview to run it here.",
    lbLabel: "Image: {0}", lbLabelNoName: "Image", lbClose: "Close", lbOpenOriginal: "Open original", lbPrev: "Previous image", lbNext: "Next image", lbCount: "{0} / {1}",
    // #1554: preview.js's words (its English is the fallback there), and the server's reasons by code.
    pvWhyOptin: "HTML previews are off on this device (this browser, at this address). Allow them from this card's ⋯ menu or the sidebar.",
    pvWhyOptinPanel: "HTML previews are off on this device (this browser, at this address).",
    pvWhyNever: "Previews are switched off on this device for this session.",
    pvWhyOrigin: "Previews are off: this page is at {0}, but the fleet believes it is at {1} (a proxy that rewrites Host). Pass the external Host through, or set web.preview_origin.",
    pvUnknownAddress: "an unknown address", pvWhyServer: "Previews are not available here.",
    pvHtmlOver: "This HTML is over 1 MiB; it is not previewed.",
    pvNoAnswer: "Preview unavailable: the preview did not answer within 3 s. If an earlier preview froze, it may still be running — open the dashboard in a new tab. Over SSH, forward the preview port too.",
    pvStoppedAnswering: "The preview stopped answering, so it was closed.", pvSwitchedOff: "Previews were switched off on this device.",
    pvAnother: "Another preview started.", pvWrongBoot: "Preview unavailable: something else answered on the preview port.",
    pvBanner: "Previews run the agent's HTML in an isolated frame. It cannot use your login, but it may be able to send data out. Only preview content you trust. A preview can slow or freeze this tab.",
    pvServer_fleetOff: "Previews are turned off for this fleet (web.preview: false).", pvServer_unchecked: "This address cannot be checked.",
    pvServer_noPort: "Previews have no port: set web.preview_port (health_port is the highest port).",
    pvServer_notListed: "Previews are not offered at {0}: list this address (with its port) in web.allowed_hosts, and set web.preview_origin.",
    pvServer_needOrigin: "Previews need web.preview_origin when the dashboard is reached through a tunnel or proxy.",
    pvServer_needHttps: "Previews need an https web.preview_origin when the dashboard is reached over https.",
    pvServer_sameOrigin: "The preview origin cannot be the dashboard's own.",
    pvServer_publicLink: "Previews are not offered over the public link. Open the dashboard on the machine running AgEnD to preview.",
    pvServer_notOffered: "Previews are not available on this page.",
    previews: "Allow HTML previews on this device",
    copy: "Copy", copyMessage: "Copy this reply", copied: "Copied", copyFailed: "Copy failed", wrap: "Wrap", showAll: "Show all {0} lines", showLess: "Show less", jumpLatest: "Latest", newBelow: "{0} new",
    disconnected: "disconnected", tick_queued: "Waiting behind another message", tick_processing: "Handed to the agent", tick_delivered: "The agent has it", tick_failed: "Not delivered", tick_cancelled: "Dropped by Stop",
    promptAnswering: "Answering…", promptGone: "This prompt is no longer open", promptFor: "{0}: {1}",
    working: "{0} is working…", stuck: "{0} looks stuck", stopReply: "Stop reply", stopReplyTitle: "Stop the current reply (like Esc) and drop the messages still waiting. The instance keeps running.", stopSent: "Stopped",
    file_empty: "empty file", file_too_large: "over 10 MB", file_too_many: "at most 5 files per message", file_too_much: "the files together would be over 25 MB", removeFile: "Remove", notSent: "Not sent:", putBack: "Put back", discard: "Discard",
    noMessages: "No messages yet", sendFirst: "Send a message to start the conversation",
    pick: "Pick an instance to start", pickHint: "Choose one in the list, or create a new one.", notFound: "No instance called “{0}”", notFoundHint: "It may have been deleted or renamed.", backToList: "Open the instance list",
    details: "Instance details", start: "Start instance", stopInstance: "Stop instance", restart: "Restart instance", delete: "Delete instance…",
    started: "{0} started", stoppedInst: "{0} stopped", restarted: "{0} restarted", instanceDeleted: "{0} was deleted",
    deleteTitle: "Delete {0}?", deleteHelp: "This removes the instance from the fleet and stops it. Its working directory is kept. Type “delete {0}” to confirm.", deleteGo: "Delete", cancel: "Cancel",
    loadFailed: "Failed to load", tour: "Tour", tourBtnTitle: "Show the web chat tour again",
    dName: "Name", dStatus: "Status", dDisplay: "Display name", dDescription: "Description", dDirectory: "Directory", dBackend: "Backend", dModel: "Model", dEffort: "Effort",
    dCost: "Cost", dCostNote: "(session accumulated)", dContext: "Context", dRate5: "Rate 5h", dRate7: "Rate 7d", dActivity: "Recent activity", dInstance: "Instance", dRuntime: "Runtime",
    // #1523 N2: Details (the Fleet side of one instance).
    dConfig: "Configuration", dBinding: "Bound to", dBindingGeneral: "the General topic of {0}", dBindingTopic: "{0}, topic {1}", dBindingNoTopic: "{0}, no topic yet",
    dBindingDefault: "{0} (the first connection, by default)", dBindingRoom: "ClassicBot room #{0} ({1})",
    dBindingNone: "not bound (web only)", dPrimary: "the first connection", dTags: "Tags", dReadOnly: "Read only — change it in Settings.",
    dEditInSettings: "Edit in Settings", dPause: "Pause", dWake: "Wake", dPaused: "{0} paused", dWoken: "{0} is waking up", dActionFailed: "That did not work — try again.",
    dNoActivity: "No activity in the last hour.", dWorking: "Working…",
    configured: "(configured)", fleetDefault: "(fleet default)",
  },
  "zh-TW": {
    cmdConfirm: "清空", cmdRunning: "執行 /{0} 中…", cmdNotCommand: "這裡沒有這個指令——按 Enter 會當成一般訊息送出。", cmdDismiss: "關閉", cmdCommands: "指令",
    cmdChoose: "選擇", cmdCurrent: "目前", chipCompact: "壓縮", chipClear: "清空…", chipContext: "已用 {0}% 的 context",
    chipModel: "模型：{0}——選擇其他", chipEffort: "推理強度：{0}——選擇其他",
    cmd_ctx: "context 用量、模型與推理強度", cmd_compact: "壓縮對話", cmd_clear: "清空對話（會先確認）",
    cmd_model: "查看或切換模型", cmd_effort: "查看或設定推理強度", cmd_cancel: "停止目前的回覆",
    cmd_btw: "不打斷目前工作的旁問", cmd_steer: "送進目前這一輪", cmd_pause: "暫停 instance",
    cmd_wake: "喚醒已暫停的 instance", cmd_save: "把對話存成檔案",
    tourTitle: "歡迎使用網頁聊天", tourStep: "{0} / {1}", tourBack: "上一步", tourNext: "下一步", tourDone: "知道了", tourSkip: "略過",
    tour1: "在清單裡選一個 instance，就能跟它對話。手機上請按 ☰ 打開清單。",
    tour2: "這和它在 Telegram 或 Discord 上的是同一段對話：在這裡送出的訊息那邊也看得到，Agent 的回覆兩邊都會出現。",
    tour3: "按 📎 附上檔案和圖片，也可以直接貼上或拖到聊天裡。",
    tour4: "Agent 工作時，輸入框會出現「中止回覆」：中斷目前的回覆，instance 本身會繼續運行。",
    tour5: "看到「等你回應」標記，表示 Agent 在終端機上等你，例如權限詢問。到它的聊天裡按按鈕回應即可。",
    a11yWorking: "{0} 開始工作", a11yIdle: "{0} 已完成", a11yReplied: "{0} 已回覆", conversationWith: "與 {0} 的對話",
    stopping: "正在中止 {0}…", awaiting: "{0} 正在等你回應", approxNote: "從終端畫面判讀，僅供參考", elapsedTitle: "從這個頁面看到它開始工作起算（約略）",
    dropHere: "放開即可附加檔案", asText: "改為文字", pasteAttached: "貼上的長文字（{0} 個字元）已改為文字檔附加", pasteKeptAsText: "附件已滿，貼上的長文字保留為一般文字",
    send: "送出", composerPlaceholder: "傳訊息給 {0}…", composerHint: "Enter 送出 · Shift+Enter 換行 · / 叫出指令 · Esc 中止回覆", attachTitle: "附加檔案（圖片、PDF、文字檔，也可以貼上或拖曳）",
    pvPreview: "預覽", pvStop: "停止", pvDownload: "下載", pvMenu: "預覽選項", pvHtml: "HTML",
    pvAllowButton: "允許預覽", pvAllow: "允許這台裝置預覽 HTML（預覽可能把資料傳出去）", pvDisallow: "不再允許這台裝置預覽 HTML",
    pvConfirm: "要允許這台裝置預覽 HTML 嗎？\n\n預覽會在隔離的框架裡執行 agent 的 HTML。它無法使用你的登入，但可能把資料傳出去，也可能讓這個分頁變慢或卡住。每次仍需要你按「預覽」。",
    pvNever: "這台裝置永不預覽 HTML", pvNeverUndo: "讓這台裝置再次可以預覽 HTML", pvStarting: "正在啟動預覽…",
    pvChanged: "預覽已停止——訊息內容變了。請再預覽一次。", pvTruncated: "內容被截斷——請 agent 改用 .html 檔案傳送。",
    pvLoading: "正在讀取檔案…", pvAttOver: "這個檔案超過 1 MiB，不提供預覽。",
    pvAttGone: "這裡已無法取得這個檔案（檔案已變更，或艦隊已重新啟動）。請 agent 再傳一次。",
    pvAttFailed: "無法讀取這個檔案，請再試一次。",
    rbGroup: "選項", rbChosen: "{0} 已選擇", rbExpired: "已逾時，請直接回覆文字",
    pvOpenPanel: "在面板中開啟", pvInPanel: "已在面板中顯示。", pvPanel: "HTML 預覽", pvSource: "來自 {0}，{1}——顯示該訊息",
    pvPage: "頁面", pvCode: "程式碼", pvReload: "重新載入", pvClose: "關閉面板", pvBack: "回到對話", pvResize: "調整預覽面板寬度",
    pvNewer: "{0} 的回覆裡有較新的版本。", pvNewerShow: "顯示", pvPanelIdle: "按「預覽」在這裡執行。",
    lbLabel: "圖片：{0}", lbLabelNoName: "圖片", lbClose: "關閉", lbOpenOriginal: "開啟原圖", lbPrev: "上一張", lbNext: "下一張", lbCount: "{0} / {1}",
    pvWhyOptin: "這台裝置（這個瀏覽器、這個網址）還沒允許 HTML 預覽。可從這張卡片的 ⋯ 選單或側欄允許。",
    pvWhyOptinPanel: "這台裝置（這個瀏覽器、這個網址）還沒允許 HTML 預覽。",
    pvWhyNever: "這台裝置在這個工作階段已關閉預覽。",
    pvWhyOrigin: "預覽已關閉：這個頁面位於 {0}，但艦隊認為它位於 {1}（有會改寫 Host 的代理）。請讓外部 Host 原樣傳入，或設定 web.preview_origin。",
    pvUnknownAddress: "未知的網址", pvWhyServer: "這裡無法使用預覽。",
    pvHtmlOver: "這段 HTML 超過 1 MiB，不提供預覽。",
    pvNoAnswer: "無法預覽：預覽在 3 秒內沒有回應。如果先前的預覽卡住了，它可能還在執行——請在新分頁開啟儀表板。透過 SSH 使用時，也要轉送預覽的連接埠。",
    pvStoppedAnswering: "預覽沒有回應，已將它關閉。", pvSwitchedOff: "這台裝置已關閉預覽。",
    pvAnother: "另一個預覽已開始。", pvWrongBoot: "無法預覽：預覽連接埠上回應的不是這個艦隊。",
    pvBanner: "預覽會在隔離的框架裡執行 agent 的 HTML。它無法使用你的登入，但可能把資料傳出去。只預覽你信任的內容。預覽可能讓這個分頁變慢或卡住。",
    pvServer_fleetOff: "這個艦隊已關閉預覽（web.preview: false）。", pvServer_unchecked: "無法確認這個網址。",
    pvServer_noPort: "預覽沒有可用的連接埠：請設定 web.preview_port（health_port 已是最大的連接埠）。",
    pvServer_notListed: "{0} 不提供預覽：請把這個網址（含連接埠）加入 web.allowed_hosts，並設定 web.preview_origin。",
    pvServer_needOrigin: "透過通道或代理開啟儀表板時，預覽需要設定 web.preview_origin。",
    pvServer_needHttps: "以 https 開啟儀表板時，預覽需要 https 的 web.preview_origin。",
    pvServer_sameOrigin: "預覽的來源不能和儀表板相同。",
    pvServer_publicLink: "公開連結不提供預覽。要預覽，請在執行 AgEnD 的那台機器上開啟儀表板。",
    pvServer_notOffered: "這個頁面不提供預覽。",
    previews: "允許這台裝置預覽 HTML",
    copy: "複製", copyMessage: "複製這則回覆", copied: "已複製", copyFailed: "複製失敗", wrap: "換行", showAll: "展開全部 {0} 行", showLess: "收合", jumpLatest: "最新", newBelow: "{0} 則新訊息",
    disconnected: "已斷線", tick_queued: "排在前一則訊息之後", tick_processing: "已交給 agent", tick_delivered: "agent 已收到", tick_failed: "未送達", tick_cancelled: "已被中止取消",
    promptAnswering: "回覆中…", promptGone: "這個提示已經結束", promptFor: "{0}：{1}",
    working: "{0} 處理中…", stuck: "{0} 似乎卡住了", stopReply: "中止回覆", stopReplyTitle: "中止目前的回覆（同 Esc），並取消還在排隊的訊息。instance 會繼續運行。", stopSent: "已中止",
    file_empty: "空檔案", file_too_large: "超過 10 MB", file_too_many: "每則訊息最多 5 個檔案", file_too_much: "檔案合計會超過 25 MB", removeFile: "移除", notSent: "未送出：", putBack: "放回輸入框", discard: "捨棄",
    noMessages: "尚無訊息", sendFirst: "傳送訊息以開始對話",
    pick: "選一個 instance 開始", pickHint: "在清單裡選一個，或建立新的。", notFound: "沒有叫「{0}」的 instance", notFoundHint: "它可能已被刪除或改名。", backToList: "打開 instance 清單",
    details: "Instance 詳細資料", start: "啟動 instance", stopInstance: "停止 instance", restart: "重新啟動 instance", delete: "刪除 instance…",
    started: "{0} 已啟動", stoppedInst: "{0} 已停止", restarted: "{0} 已重新啟動", instanceDeleted: "{0} 已刪除",
    deleteTitle: "要刪除 {0} 嗎？", deleteHelp: "這會把 instance 從 fleet 移除並停止它，工作目錄會保留。請輸入「delete {0}」確認。", deleteGo: "刪除", cancel: "取消",
    loadFailed: "載入失敗", tour: "導覽", tourBtnTitle: "再看一次網頁聊天導覽",
    dName: "名稱", dStatus: "狀態", dDisplay: "顯示名稱", dDescription: "說明", dDirectory: "目錄", dBackend: "Backend", dModel: "模型", dEffort: "Effort",
    dCost: "花費", dCostNote: "（本次 session 累計）", dContext: "Context", dRate5: "5 小時額度", dRate7: "7 天額度", dActivity: "最近活動", dInstance: "Instance", dRuntime: "執行環境",
    dConfig: "設定", dBinding: "綁定", dBindingGeneral: "{0} 的 General topic", dBindingTopic: "{0}，topic {1}", dBindingNoTopic: "{0}，尚未綁定 topic",
    dBindingDefault: "{0}（預設：第一個連線）", dBindingRoom: "ClassicBot 房間 #{0}（{1}）",
    dBindingNone: "未綁定（只用網頁）", dPrimary: "第一個連線", dTags: "標籤", dReadOnly: "這裡只能檢視——請到設定修改。",
    dEditInSettings: "到設定編輯", dPause: "暫停", dWake: "喚醒", dPaused: "{0} 已暫停", dWoken: "{0} 正在喚醒", dActionFailed: "沒有成功，請再試一次。",
    dNoActivity: "最近一小時沒有活動。", dWorking: "處理中…",
    configured: "（設定值）", fleetDefault: "（fleet 預設）",
  },
});
