// #1408 step 3: Settings' strings (the settings.* namespace). Ported from settings.html's table, emoji prefixes dropped
// (icons are the app's own SVGs now), plus the panel's own.
import { register } from "/assets/app-i18n.js";

register("settings", {
  en: {
    title: "Settings",
    myAgents: "My Agents",
    bots: "Bots",
    classicChannels: "ClassicBot Channels",
    noClassic: "No ClassicBot channels — start one with /start in a chat.",
    publicLink: "Offer temporary public web links",
    publicLinkHint: "Explicit admin consent on every request. Cloudflare handles TLS; link users have full web-admin access. No preview exposure.",
    publicTtl: "Public link minutes (1–480)",
    publicProtocol: "Tunnel protocol",
    webEcho: "Web echo",
    webEchoHint: "Copies web messages to the bound Telegram or Discord topic. ClassicBot rooms are excluded.",
    general: "General Settings",
    advanced: "Advanced",
    new: "New",
    add: "Add",
    edit: "Edit",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    start: "Start",
    stop: "Stop",
    backend: "Backend",
    model: "Model",
    workingDir: "Working directory",
    channelBinding: "Channel binding",
    description: "Description",
    systemPrompt: "System prompt",
    tags: "Tags",
    generalTopicField: "General topic (fleet dispatcher)",
    runtimeResources: "Runtime & Resources",
    autoPause: "Auto-pause after",
    minutes: "minutes",
    inheritDefault: "Inherit from defaults",
    statusEmojis: "Status emojis",
    statusEmojisInstance: "This agent's status emojis (override the connection's)",
    statusEmojisChannel: "Status emojis for this connection's bots",
    se_received: "Received",
    se_queued: "Queued",
    se_processing: "Processing",
    se_delivered: "Delivered",
    se_failed: "Failed",
    se_progress_prefix: "Progress prefix",
    se_photo: "Photo saved",
    se_attachment: "File saved",
    se_src_instance: "agent",
    se_src_platform: "connection",
    se_src_builtin: "default",
    se_pick: "Pick…",
    se_useDefault: "Use the default",
    se_fallback: "the default is used instead",
    se_unicode: "Emoji",
    se_telegramOnly: "Telegram allows only these reactions",
    se_serverEmojis: "Server emojis",
    se_noServerEmojis: "No custom emojis on this server.",
    se_primaryServer: "primary",
    se_externalEmojiHint: "Another server's emoji needs the bot's Use External Emojis permission in the channel it reacts in.",
    se_unavailable: "unavailable",
    se_hint: "Empty keeps the default. The preview is resolved by AgEnD exactly as the bot will react.",
    detection: "Detection",
    startup: "Startup",
    backendSection: "Backend",
    advancedSection: "Advanced",
    hangEnabled: "Hang detector enabled",
    hangTimeout: "Stuck timeout",
    agentMode: "Agent mode",
    toolSet: "Tool set",
    toolProgress: "Tool progress",
    crossInstanceVisibility: "Bot-to-bot messages in topics",
    crossInstanceVisibilityHint: "full: the whole message · summary: one line · hidden: nothing. Messages are always delivered; the Mirror Topic still shows them.",
    replyCompletionGuard: "Require a delivered reply",
    replyGuardSupported: "Available for Claude Code and Kiro legacy/TUI in MCP mode.",
    replyGuardUnsupported: "Stored but inactive: {0} in {1} mode does not support reply-drop recovery.",
    logLevel: "Log level",
    concurrency: "Startup concurrency",
    staggerDelay: "Stagger delay",
    lightweight: "Lightweight mode",
    modelFailover: "Fallback model",
    displayName: "Display name",
    pause: "Pause",
    wake: "Wake",
    accessMode: "Access mode",
    affected: "Affected instances",
    webEchoGroupConfirm: "This looks like a group channel: enabling posts every web message to this instance where all channel members can read it. Enable web echo?",
    language: "Language (bot replies)",
    defaultBackend: "Default backend",
    defaultModel: "Default model",
    allowedUsers: "Allowed users (primary bot)",
    localeAuto: "Auto (follow system)",
    classicAdmins: "ClassicBot admins",
    allowedGuilds: "Allowed guilds",
    type: "Type",
    adapterId: "Adapter id",
    tokenEnv: "Bot token env var",
    groupId: "Group / guild id",
    nameField: "Name",
    envHint: "Put the actual token in ~/.agend/.env under this env var, then Reload Fleet.",
    noAgents: "No agents yet — click + New.",
    noBots: "No bots configured.",
    currentVersion: "Current version",
    helpTitle: "Help",
    helpButton: "Help",
    saved: "Saved",
    failed: "Failed",
    actionFailed: "{0} failed",
    noAgentMatch: "No agents match \"{0}\".",
    deleteAgent: "Delete agent \"{0}\"? This will be applied only after you confirm the pending changes.",
    nameRequired: "name required",
    tokenEnvRequired: "token env required",
    removeBot: "Remove bot \"{0}\"? (the token in .env is left untouched)",
    applying: "Applying changes…",
    applyDone: "Changes applied",
    applyPartial: "Some changes failed",
    applyClose: "Close",
    settingsButton: "Settings",
    modalDone: "Stage change",
    wizardButton: "Setup wizard",
    wizardTitle: "Set up AgEnD",
    wizardStep: "Step {0} of {1}",
    wizardRerun: "A fleet is already configured — finishing replaces the connection that uses the same token variable.",
    wizardBack: "Back",
    wizardNext: "Next",
    wizardFinish: "Create and start",
    wizardBackend: "Backend",
    wizardBackendFound: "Found on this host: {0}",
    wizardBackendNone: "No backend CLI found on this host — install one first.",
    wizardAgentName: "First agent name",
    wizardNeedDir: "Enter an absolute working directory.",
    wizardTelegramHint: "Create a bot with @BotFather, then add it to a group.",
    wizardDiscordHint: "Create an application in the Discord developer portal and invite the bot to your server.",
    wizardToken: "Bot token",
    wizardTokenTelegram: "From @BotFather. It is written to ~/.agend/.env and never shown again.",
    wizardTokenDiscord: "From the Bot tab of your application. It is written to ~/.agend/.env and never shown again.",
    wizardVerify: "Verify",
    wizardVerifying: "Asking the provider…",
    wizardDetect: "Detect from a message",
    wizardDetectHint: "Or post any message in the group and press Detect.",
    wizardWaitingStart: "Waiting for a message in the group…",
    wizardNoStartYet: "No group message yet — post one and press Detect again.",
    wizardGeneralChannel: "General channel id",
    wizardAdminUser: "Your user id (becomes the first allowed user)",
    wizardNeedVerify: "Verify the token before continuing.",
    wizardPlanLoading: "Building the plan…",
    wizardWillWrite: "This will be written:",
    wizardEnvKeys: "And into ~/.agend/.env: {0}",
    wizardEnvPerms: "~/.agend/.env is readable by other users on this host.",
    guildIdField: "Guild id",
    groupIdField: "Group id",
    notSet: "(not set)",
    deleteBot: "Delete this bot",
    noAllowedUsers: "no allowed users",
    searchAll: "Search agents, bots, channels…",
    accessMovedHint: "Who may use the bot is set on the connection itself — open Settings on \"{0}\" under Connections & Bots.",
    applyRestartNeeded: "Saved — restart AgEnD to apply",
    applyNoChange: "no change needed",
    applyRestartHint: "This change needs AgEnD itself restarted. You can restart it here, or run /restart in your chat channel.",
    applyBusy: "AgEnD is already reloading its configuration. Your changes are saved — try Apply again in a moment.",
    restartFleetButton: "Restart AgEnD",
    restartFleetConfirm: "Restart AgEnD now?\n\nEvery agent stops and starts again, work in progress is interrupted, and the panel is unreachable for up to a minute. A notice is posted to your chat channel.",
    restartFleetStarted: "Restarting AgEnD — this page keeps checking.",
    restartFleetBusy: "Restarting…",
    restartFleetTitle: "Restarting AgEnD…",
    restartFleetWaiting: "AgEnD is restarting. This page keeps checking and will say when it is back — there is nothing to press.",
    working: "Working…",
    restartFleetRefused: "Restart refused: {0}",
    restartFleetRateLimited: "Restart refused: {0} (try again in about {1} minutes)",
    signatureMismatch: "fleet.yaml and the running configuration disagree on: {0}. Restarting will not clear this — check daemon.log first.",
    applyStillWorking: "Still restarting ({0}s) — AgEnD is still working; this page keeps checking.",
    applyLostJob: "Lost track of this apply (the fleet may have restarted). Reload the page to see the current state.",
    changesPending: "{0} change(s) not applied",
    impactNow: "Immediately",
    impactAgent: "Restart this Agent",
    impactFleet: "Restart AgEnD",
    queued: "Queued: {0}",
    applyFailed: "Apply failed",
    changesApplied: "Changes applied. AgEnD is reconciling affected Agents.",
    reviewChanges: "Review changes",
    backendUnavailable: "{0} (removed — choose another backend)",
    readyApply: "Ready to apply",
    copied: "Copied",
    expectedMapping: "expected a mapping",
    configLoadFailed: "Failed to load config — open the Settings link again.",
    confirmOpenAccess: "Open access allows anyone in this channel to operate the bot. Continue?",
    confirmLockedEmpty: "Locked access has no allowed users. This may leave nobody able to administer the bot. Continue?",
    accessLockedEmpty: "Locked mode has no allowed users; add at least one administrator to avoid lockout.",
    accessChangeCancelled: "Access mode change cancelled",
    mustNonNegative: "Must be 0 or greater",
    mustPositive: "Must be greater than 0",
    nonnegativeInteger: "Must be a non-negative integer",
    failoverEmpty: "Empty list disables failover",
    concurrencyRange: "Must be an integer from 1 to 20",
    concurrencyWarning: "May exceed CPU capacity on smaller hosts",
    staggerRange: "Must be between 0 and 30000",
    staggerWarning: "Very low values can cause startup spikes",
    sec_agents: "Agents",
    sec_bots: "Connections",
    sec_classic: "ClassicBot",
    sec_general: "General",
    sec_advanced: "Developer",
    stRunning: "Running",
    stPaused: "Paused",
    stCrashed: "Crashed",
    stStopped: "Stopped",
    exec_idle: "Idle",
    exec_working: "Working",
    exec_stuck: "Stuck",
    exec_paused: "Paused",
    exec_crashed: "Crashed",
    exec_stopped: "Stopped",
    exec_running: "Running",
    countAgents: "{0} agents",
    countBots: "{0} connections",
    countRooms: "{0} rooms",
    newAgent: "New agent",
    newBot: "New connection",
    effortTag: "effort: {0}",
    deleteAgentMenu: "Delete agent",
    deleteAgentLabel: "Delete {0}",
    updateAgent: "Update {0}",
    updateDefaults: "Update agent defaults",
    updateClassicDefaults: "Update ClassicBot defaults and access",
    updateAccess: "Update {0} access",
    updateEmojis: "Update {0} status emojis",
    updateAccessEmojis: "Update {0} access & status emojis",
    connected: "Connected",
    problem: "Problem",
    groupTag: "group {0}",
    guildTag: "guild {0}",
    accessTag: "access: {0}",
    tokenConfigured: "Token configured",
    tokenMissing: "Token missing",
    noTokenEnv: "(no token env)",
    providerKeys: "Provider API keys",
    noProviderVerifiers: "No provider API-key verifiers available.",
    keyConfigured: "Key configured",
    keyNotConfigured: "Not configured",
    providerKeyInput: "{0} API key",
    providerKeyLabel: "{0} API key",
    verifyApply: "Verify & apply",
    unsupportedVerifier: "Unsupported verifier",
    unsupportedVerifierHint: "This provider cannot be safely verified here, so no key input is offered.",
    enterKeyFirst: "Enter a key first.",
    verifying: "Verifying…",
    verified: "Verified",
    verifyFailed: "Verification failed",
    applyingKey: "Applying…",
    keyAppliedNextUse: "Saved — new processes will use it",
    keyApplied: "Applied",
    keyRolledBack: "Rolled back",
    keyRollbackFailed: "Rollback failed",
    accessTitle: "Access",
    webChat: "Web chat",
    defaultsTitle: "Defaults",
    classicBackend: "ClassicBot default backend",
    whoUsesClassic: "Who can use ClassicBot",
    userIdPlaceholder: "user id",
    guildIdPlaceholder: "guild id",
    tagPlaceholder: "tag",
    removeItem: "Remove {0}",
    inheritPlaceholder: "(inherit default)",
    zeroDisabled: "0 = off",
    optional: "optional",
    collabMode: "Collaboration mode",
    contextLines: "Context lines",
    refresh: "Refresh",
    generalChannelId: "General channel id",
    forumTopicId: "Forum topic id",
    groupRequired: "A group or guild id is needed.",
    bindingHint: "The target is checked with the existing bot token before the binding changes.",
    bindingButton: "Verify the new binding",
    bindingVerifying: "Verifying the target…",
    bindingVerifyFailed: "Binding verification failed",
    bindingVerified: "Verified {0}",
    bindingConfirm: "Rebind this connection to {0}?",
    bindingNotApplied: "Verified; not applied.",
    bindingApplying: "Applying the binding…",
    bindingApplyFailed: "Applying the binding failed",
    bindingApplied: "Binding applied",
    bindingRolledBack: "Binding rolled back",
    bindingRollbackFailed: "Binding rollback failed",
    bindingUnknown: "Unknown binding result",
    stillApplying: "Still applying — check again shortly",
    bindingLabel: "Rebind {0}",
    tokenField: "Bot token (never stored in the browser)",
    tokenPlaceholder: "Paste a new bot token to rotate it",
    tokenHint: "AgEnD verifies the token, then applies it by replacing the running adapter. It is never shown again.",
    tokenButton: "Stage the new token",
    tokenRequired: "Paste a token first.",
    tokenQueued: "Staged — press Apply changes.",
    rotateToken: "Rotate the {0} token",
    addBotLabel: "Add connection {0}",
    removeBotLabel: "Remove connection {0}",
    pendingRegion: "Changes not applied yet",
    discard: "Discard",
    applyChanges: "Apply changes",
    discardOnLeave: "Discard {0} pending changes?",
    applyBusyLocal: "An Apply is still running — wait for it to finish.",
    applyStepFailed: "Stopped at a change: {0}. The changes after it were not applied; they are staged again.",
    stepWaiting: "Waiting for confirmation in chat",
    stepSkipped: "Not applied",
    viaRestart: "(restart)",
    format: "Format",
    editMode: "Edit",
    viewMode: "View",
    copy: "Copy",
    devEditor: "fleet.yaml editor",
    devApply: "Apply & save",
    devApplyHint: "Writes these settings and applies them, like Apply changes.",
    noChanges: "Nothing to change.",
    wizardCommitting: "Writing the configuration…",
    wizardPlatform: "Platform",
    discordUserPlaceholder: "your Discord user id",
    telegramUserPlaceholder: "your Telegram user id",
    help1: "Agents: each agent's settings, Start/Stop, Pause/Wake, and New agent.",
    help2: "Connections: who may use each bot, its binding, its status emojis, a new token; and provider API keys.",
    help3: "ClassicBot: each room's backend, model and options.",
    help4: "General: defaults for every agent, ClassicBot defaults and web chat. Review changes stages them.",
    help5: "Changes are staged, then applied together with Apply changes. Each shows what it costs: immediately, an agent restart, or an AgEnD restart.",
    help6: "A change to access, secrets or connections waits for a fleet admin to confirm it in chat before it applies.",
  },
  "zh-TW": {
    statusEmojis: "狀態 emoji",
    statusEmojisInstance: "此 Agent 的狀態 emoji（覆蓋連線設定）",
    statusEmojisChannel: "此連線 bot 的狀態 emoji",
    se_received: "已收到",
    se_queued: "排隊中",
    se_processing: "處理中",
    se_delivered: "已送達",
    se_failed: "失敗",
    se_progress_prefix: "進度前綴",
    se_photo: "已存圖片",
    se_attachment: "已存檔案",
    se_src_instance: "Agent",
    se_src_platform: "連線",
    se_src_builtin: "預設",
    se_pick: "選擇…",
    se_useDefault: "使用預設",
    se_fallback: "改用預設值",
    se_unicode: "Emoji",
    se_telegramOnly: "Telegram 只允許這些反應",
    se_serverEmojis: "伺服器 emoji",
    se_noServerEmojis: "此伺服器沒有自訂 emoji。",
    se_primaryServer: "主伺服器",
    se_externalEmojiHint: "使用其他伺服器的 emoji，bot 在要加反應的頻道需有「使用外部表情符號」權限。",
    se_unavailable: "無法使用",
    se_hint: "留空即使用預設值。預覽由 AgEnD 依 bot 實際 react 的方式解析。",
    title: "設定",
    myAgents: "我的 Agent",
    bots: "機器人",
    classicChannels: "ClassicBot 頻道",
    noClassic: "沒有 ClassicBot 頻道 — 在聊天中用 /start 建立。",
    publicLink: "提供臨時公開網頁連結",
    publicLinkHint: "每次都需管理員明確啟用。Cloudflare 終止 TLS；登入者具有完整網頁管理權限，不公開 preview。",
    publicTtl: "公開連結分鐘數（1–480）",
    publicProtocol: "Tunnel 協定",
    webEcho: "Web 同步",
    webEchoHint: "將網頁訊息複製到綁定的 Telegram 或 Discord 主題，不包含 ClassicBot 群組。",
    general: "一般設定",
    advanced: "進階",
    new: "新增",
    add: "加入",
    edit: "編輯",
    close: "關閉",
    save: "儲存",
    cancel: "取消",
    create: "建立",
    start: "啟動",
    stop: "停止",
    backend: "後端",
    model: "模型",
    workingDir: "工作目錄",
    channelBinding: "頻道綁定",
    description: "描述",
    systemPrompt: "System prompt",
    tags: "標籤",
    generalTopicField: "General topic（fleet 分派器）",
    runtimeResources: "執行環境與資源",
    autoPause: "閒置後自動暫停",
    minutes: "分鐘",
    inheritDefault: "沿用全域預設值",
    detection: "偵測",
    startup: "啟動",
    backendSection: "後端",
    advancedSection: "進階",
    hangEnabled: "啟用卡住偵測",
    hangTimeout: "卡住逾時",
    agentMode: "Agent 模式",
    toolSet: "工具集",
    toolProgress: "工具進度",
    crossInstanceVisibility: "Agent 之間的訊息在主題中",
    crossInstanceVisibilityHint: "full：完整訊息 · summary：一行摘要 · hidden：不顯示。訊息一律照常送達，Mirror Topic 也照常顯示。",
    replyCompletionGuard: "要求送出回覆",
    replyGuardSupported: "Claude Code 與 Kiro legacy/TUI 的 MCP 模式可用。",
    replyGuardUnsupported: "設定會保留，但不會生效：{0} 的 {1} 模式不支援回覆遺失補救。",
    logLevel: "Log 等級",
    concurrency: "啟動併發數",
    staggerDelay: "錯開延遲",
    lightweight: "輕量模式",
    modelFailover: "備援模型",
    displayName: "顯示名稱",
    pause: "暫停",
    wake: "喚醒",
    accessMode: "存取模式",
    affected: "受影響 instances",
    webEchoGroupConfirm: "這看起來是群組頻道：開啟後，這個 instance 的每則 web 訊息都會貼到所有頻道成員看得到的地方。確定要開啟 web echo？",
    language: "語言（bot 回覆）",
    defaultBackend: "預設後端",
    defaultModel: "預設模型",
    allowedUsers: "允許使用者（主 bot）",
    localeAuto: "自動（跟隨系統）",
    classicAdmins: "ClassicBot 管理員",
    allowedGuilds: "允許的伺服器",
    type: "類型",
    adapterId: "Adapter id",
    tokenEnv: "Bot token 環境變數",
    groupId: "群組 / guild id",
    nameField: "名稱",
    envHint: "把實際 token 放到 ~/.agend/.env 的這個環境變數下，然後點重新載入。",
    noAgents: "還沒有 agent — 點 + 新增。",
    noBots: "尚未設定機器人。",
    currentVersion: "目前版本",
    helpTitle: "使用說明",
    helpButton: "使用說明",
    saved: "已儲存",
    failed: "失敗",
    actionFailed: "{0}失敗",
    noAgentMatch: "沒有符合「{0}」的 Agent。",
    deleteAgent: "確定刪除 Agent「{0}」嗎？只有在確認套用待處理變更後才會生效。",
    nameRequired: "必須填寫名稱",
    tokenEnvRequired: "必須填寫 token 環境變數",
    removeBot: "確定移除機器人「{0}」嗎？（.env 中的 token 會保留）",
    applying: "正在套用變更…",
    applyDone: "變更已套用",
    applyPartial: "有部分變更失敗",
    applyClose: "關閉",
    settingsButton: "設定",
    modalDone: "加入待套用",
    wizardButton: "設定精靈",
    wizardTitle: "設定 AgEnD",
    wizardStep: "第 {0} 步，共 {1} 步",
    wizardRerun: "已經有設定好的 fleet —— 完成後會取代使用相同 token 變數的那個連線。",
    wizardBack: "上一步",
    wizardNext: "下一步",
    wizardFinish: "建立並啟動",
    wizardBackend: "後端",
    wizardBackendFound: "在這台主機上找到：{0}",
    wizardBackendNone: "這台主機上找不到任何後端 CLI —— 請先安裝一個。",
    wizardAgentName: "第一個 agent 名稱",
    wizardNeedDir: "請輸入絕對路徑的工作目錄。",
    wizardTelegramHint: "用 @BotFather 建立 bot，然後把它加進一個群組。",
    wizardDiscordHint: "在 Discord 開發者後台建立應用程式，並把 bot 邀請到你的伺服器。",
    wizardToken: "Bot token",
    wizardTokenTelegram: "來自 @BotFather。會寫入 ~/.agend/.env，之後不會再顯示。",
    wizardTokenDiscord: "來自應用程式的 Bot 分頁。會寫入 ~/.agend/.env，之後不會再顯示。",
    wizardVerify: "驗證",
    wizardVerifying: "正在向平台確認…",
    wizardDetect: "從訊息偵測",
    wizardDetectHint: "或在群組裡發任一則訊息，然後按「從訊息偵測」。",
    wizardWaitingStart: "等待群組訊息中…",
    wizardNoStartYet: "還沒收到群組訊息 —— 發一則之後再按一次。",
    wizardGeneralChannel: "General 頻道 id",
    wizardAdminUser: "你的 user id（會成為第一個允許使用者）",
    wizardNeedVerify: "請先驗證 token 再繼續。",
    wizardPlanLoading: "正在產生方案…",
    wizardWillWrite: "將寫入：",
    wizardEnvKeys: "以及寫入 ~/.agend/.env：{0}",
    wizardEnvPerms: "~/.agend/.env 目前其他使用者也讀得到。",
    guildIdField: "Guild id",
    groupIdField: "群組 id",
    notSet: "（未設定）",
    deleteBot: "刪除這個機器人",
    noAllowedUsers: "沒有允許的使用者",
    searchAll: "搜尋 agent、機器人、頻道…",
    accessMovedHint: "誰可以使用 bot 是在連線本身設定 —— 請到「連線與機器人」開啟「{0}」的設定。",
    applyRestartNeeded: "已儲存 —— 需要重新啟動 AgEnD 才會生效",
    applyNoChange: "無需變更",
    applyRestartHint: "此變更需要重新啟動 AgEnD 本身。可以在這裡重新啟動，或在聊天頻道執行 /restart。",
    applyBusy: "AgEnD 正在重新載入設定。你的變更已儲存，請稍候再按一次套用。",
    restartFleetButton: "重新啟動 AgEnD",
    restartFleetConfirm: "現在重新啟動 AgEnD？\n\n所有 agent 都會停止再啟動，進行中的工作會被中斷，面板會有最多約一分鐘無法連線。聊天頻道會收到一則通知。",
    restartFleetStarted: "AgEnD 重新啟動中 —— 此頁面會持續確認。",
    restartFleetBusy: "重啟中…",
    restartFleetTitle: "AgEnD 重新啟動中…",
    restartFleetWaiting: "AgEnD 正在重新啟動。此頁面會持續確認，恢復後會告訴你 —— 不需要再按任何按鈕。",
    working: "執行中…",
    restartFleetRefused: "重新啟動被拒絕：{0}",
    restartFleetRateLimited: "重新啟動被拒絕：{0}（約 {1} 分鐘後可再試）",
    signatureMismatch: "fleet.yaml 與執行中的設定在這些項目上不一致：{0}。重新啟動無法解決，請先查看 daemon.log。",
    applyStillWorking: "仍在重啟中（{0} 秒）—— AgEnD 還在處理，此頁面會持續確認。",
    applyLostJob: "已追蹤不到這次套用（AgEnD 可能重啟過）。請重新整理頁面查看目前狀態。",
    changesPending: "有 {0} 項變更尚未套用",
    impactNow: "立即生效",
    impactAgent: "重新啟動此 Agent",
    impactFleet: "重新啟動 AgEnD",
    queued: "已加入待套用：{0}",
    applyFailed: "套用失敗",
    changesApplied: "變更已套用，AgEnD 正在協調受影響的 Agent。",
    reviewChanges: "檢查變更",
    backendUnavailable: "{0}（已移除，請選擇其他 backend）",
    readyApply: "可套用變更",
    copied: "已複製",
    expectedMapping: "預期為 mapping",
    configLoadFailed: "載入設定失敗 — 請重新開啟 Settings 連結。",
    confirmOpenAccess: "Open 模式會允許此頻道中的所有人操作 bot，確定要繼續嗎？",
    confirmLockedEmpty: "Locked 模式目前沒有允許的使用者，可能導致沒有人能管理 bot，確定要繼續嗎？",
    accessLockedEmpty: "Locked 模式沒有允許的使用者；建議至少加入一位管理員，避免無法操作。",
    accessChangeCancelled: "已取消 Access Mode 變更",
    mustNonNegative: "必須為 0 或更大的數值",
    mustPositive: "必須大於 0",
    nonnegativeInteger: "必須是非負整數",
    failoverEmpty: "空白清單會停用模型備援",
    concurrencyRange: "必須是 1 到 20 的整數",
    concurrencyWarning: "在較小的主機上可能超出 CPU 負荷",
    staggerRange: "必須介於 0 到 30000",
    staggerWarning: "數值太低可能造成啟動尖峰",
    sec_agents: "Agent",
    sec_bots: "連線",
    sec_classic: "ClassicBot",
    sec_general: "一般",
    sec_advanced: "開發者",
    stRunning: "執行中",
    stPaused: "已暫停",
    stCrashed: "已當掉",
    stStopped: "已停止",
    exec_idle: "閒置",
    exec_working: "工作中",
    exec_stuck: "卡住",
    exec_paused: "已暫停",
    exec_crashed: "已當掉",
    exec_stopped: "已停止",
    exec_running: "執行中",
    countAgents: "{0} 個 agent",
    countBots: "{0} 個連線",
    countRooms: "{0} 個房間",
    newAgent: "新增 agent",
    newBot: "新增連線",
    effortTag: "effort：{0}",
    deleteAgentMenu: "刪除 agent",
    deleteAgentLabel: "刪除 {0}",
    updateAgent: "更新 {0}",
    updateDefaults: "更新 agent 預設值",
    updateClassicDefaults: "更新 ClassicBot 預設值與存取",
    updateAccess: "更新 {0} 的存取",
    updateEmojis: "更新 {0} 的狀態表情",
    updateAccessEmojis: "更新 {0} 的存取與狀態表情",
    connected: "已連線",
    problem: "有問題",
    groupTag: "群組 {0}",
    guildTag: "伺服器 {0}",
    accessTag: "存取：{0}",
    tokenConfigured: "已設定 token",
    tokenMissing: "缺少 token",
    noTokenEnv: "（沒有 token 環境變數）",
    providerKeys: "供應商 API key",
    noProviderVerifiers: "沒有可用的 API key 驗證器。",
    keyConfigured: "已設定 key",
    keyNotConfigured: "尚未設定",
    providerKeyInput: "{0} API key",
    providerKeyLabel: "{0} API key",
    verifyApply: "驗證並套用",
    unsupportedVerifier: "不支援的驗證器",
    unsupportedVerifierHint: "這個供應商無法在這裡安全驗證，因此不提供輸入欄位。",
    enterKeyFirst: "請先輸入 key。",
    verifying: "驗證中…",
    verified: "已驗證",
    verifyFailed: "驗證失敗",
    applyingKey: "套用中…",
    keyAppliedNextUse: "已儲存——新的程序會使用它",
    keyApplied: "已套用",
    keyRolledBack: "已還原",
    keyRollbackFailed: "還原失敗",
    accessTitle: "存取",
    webChat: "網頁聊天",
    defaultsTitle: "預設值",
    classicBackend: "ClassicBot 預設 backend",
    whoUsesClassic: "誰可以使用 ClassicBot",
    userIdPlaceholder: "使用者 id",
    guildIdPlaceholder: "伺服器 id",
    tagPlaceholder: "標籤",
    removeItem: "移除 {0}",
    inheritPlaceholder: "（沿用預設）",
    zeroDisabled: "0 = 關閉",
    optional: "選填",
    collabMode: "協作模式",
    contextLines: "上下文行數",
    refresh: "重新整理",
    generalChannelId: "General 頻道 id",
    forumTopicId: "論壇主題 id",
    groupRequired: "需要群組或伺服器 id。",
    bindingHint: "變更綁定前，會先用現有的 bot token 檢查目標。",
    bindingButton: "驗證新的綁定",
    bindingVerifying: "正在驗證目標…",
    bindingVerifyFailed: "綁定驗證失敗",
    bindingVerified: "已驗證 {0}",
    bindingConfirm: "要把這個連線改綁到 {0} 嗎？",
    bindingNotApplied: "已驗證，尚未套用。",
    bindingApplying: "正在套用綁定…",
    bindingApplyFailed: "套用綁定失敗",
    bindingApplied: "綁定已套用",
    bindingRolledBack: "綁定已還原",
    bindingRollbackFailed: "綁定還原失敗",
    bindingUnknown: "未知的綁定結果",
    stillApplying: "仍在套用——稍後再看",
    bindingLabel: "改綁 {0}",
    tokenField: "Bot token（絕不存在瀏覽器）",
    tokenPlaceholder: "貼上新的 bot token 以更換",
    tokenHint: "AgEnD 會先驗證 token，再替換執行中的 adapter 來套用。之後不會再顯示。",
    tokenButton: "暫存新的 token",
    tokenRequired: "請先貼上 token。",
    tokenQueued: "已暫存——請按「套用變更」。",
    rotateToken: "更換 {0} token",
    addBotLabel: "新增連線 {0}",
    removeBotLabel: "移除連線 {0}",
    pendingRegion: "尚未套用的變更",
    discard: "捨棄",
    applyChanges: "套用變更",
    discardOnLeave: "要捨棄 {0} 項尚未套用的變更嗎？",
    applyBusyLocal: "還有一次套用在進行中——請等它完成。",
    applyStepFailed: "在某項變更停下：{0}。之後的變更沒有套用，已重新暫存。",
    stepWaiting: "等待在聊天中確認",
    stepSkipped: "未套用",
    viaRestart: "（重新啟動）",
    format: "格式",
    editMode: "編輯",
    viewMode: "檢視",
    copy: "複製",
    devEditor: "fleet.yaml 編輯器",
    devApply: "套用並儲存",
    devApplyHint: "寫入這些設定並套用，和「套用變更」相同。",
    noChanges: "沒有需要變更的內容。",
    wizardCommitting: "正在寫入設定…",
    wizardPlatform: "平台",
    discordUserPlaceholder: "你的 Discord 使用者 id",
    telegramUserPlaceholder: "你的 Telegram 使用者 id",
    help1: "Agent：每個 agent 的設定、啟動/停止、暫停/喚醒，以及新增 agent。",
    help2: "連線：誰可以使用各個 bot、它的綁定、狀態表情、新的 token；以及供應商 API key。",
    help3: "ClassicBot：每個房間的 backend、model 與選項。",
    help4: "一般：所有 agent 的預設值、ClassicBot 預設值與網頁聊天。「檢查變更」會把它們暫存。",
    help5: "變更會先暫存，再用「套用變更」一起套用。每項都會標示代價：立即生效、重新啟動 agent，或重新啟動 AgEnD。",
    help6: "存取、密鑰或連線的變更，要等 fleet 管理員在聊天中確認後才會套用。",
  },
});
