// The View panel's words (the view.* namespace of the app's one dictionary, #1408 §4), in English and zh-TW. Public
// (/assets/): an anonymous reader of /view sees them too. Mostly the old view.html dictionary, including the AI usage
// keys the server's usage API refers to by name (usage.*).
import { register } from "./app-i18n.js";

register("view", {
 "en": {
  "editProfile": "Edit profile",
  "save": "Save",
  "cancel": "Cancel",
  "filterPh": "Filter: name, model, backend",
  "filterClear": "Clear filter",
  "filterNone": "No instance matches",
  "filterShown": "shown",
  "filterStatus": "Status",
  "filterCli": "CLI",
  "filterFacetsReset": "Clear",
  "displayName": "Display name",
  "role": "Role",
  "description": "Description",
  "saveHint": "Saving needs a signed-in session. Send /dashboard to your AgEnD bot for a sign-in code.",
  "helpTitle": "📖 Help",
  "help1": "Pick an instance in the list: its live terminal shows here.",
  "help2": "Click a group's name to fold it or open it again.",
  "help3": "Edit profile changes the display name, role, description and avatar.",
  "help5": "Text size cycles Fit → S → M → L. S, M and L are the size every page shares; Fit sizes the terminal to its box.",
  "densityFit": "Fit",
  "densityComfortable": "Comfortable",
  "densityCompact": "Compact",
  "densityLabel": "Font density",
  "usageTitle": "📊 AI Usage",
  "usageEmpty": "No AI CLI logins found on this machine.",
  "usageUpdated": "updated",
  "usageRefresh": "Refresh",
  "usageHigh": "high",
  "usageNear": "near limit",
  "usageMoveUp": "Move up",
  "usageMoveDown": "Move down",
  "tooltipBackend": "Backend: {value}",
  "tooltipStatus": "Status: {value}",
  "tooltipContext": "Context: {value}",
  "tooltipModel": "Model: {value}",
  "tooltipEffort": "Effort: {value}",
  "tooltipCost": "Cost: {value}",
  "tooltipUnavailable": "Unavailable",
  "statusRunning": "Running",
  "statusPaused": "Paused",
  "statusStopped": "Stopped",
  "statusCrashed": "Crashed",
  "statusUnknown": "Unknown",
  "usageResets": "resets in {t}",
  "usageSoon": "resets soon",
  "usageFail": "Could not load usage data.",
  "usage.title": "AI Subscription Usage",
  "usage.title_plain": "AI subscription usage",
  "usage.empty_active": "No active backends with usage tracking",
  "usage.not_logged_in": "not logged in",
  "usage.error_fallback": "error",
  "usage.no_data": "no data",
  "usage.reset.in": "resets in {0}",
  "usage.reset.soon": "resets soon",
  "usage.ticket_expiry": "🎫 Nearest expiry: {0} (in {1})",
  "usage.duration.days_hours": "{0}d {1}h",
  "usage.duration.hours_minutes": "{0}h {1}m",
  "usage.duration.minutes": "{0}m",
  "usage.metric.session": "Session",
  "usage.metric.weekly": "Weekly",
  "usage.metric.monthly": "Monthly",
  "usage.metric.days_window": "{0}-day window",
  "usage.metric.named": "{0}",
  "usage.metric.named_session": "{0} (session)",
  "usage.metric.named_weekly": "{0} (weekly)",
  "usage.metric.named_monthly": "{0} (monthly)",
  "usage.metric.named_days": "{0} ({1}d)",
  "usage.metric.extra_usage": "Extra usage",
  "usage.metric.rate_limit_resets": "Rate limit resets",
  "usage.metric.credits": "Credits",
  "usage.metric.weekly_limit": "Weekly limit",
  "usage.metric.pay_as_you_go": "Pay as you go",
  "usage.metric.bonus_credits": "Bonus credits",
  "usage.metric.overage_charges": "Overage charges",
  "usage.metric.pay_per_use": "Pay-per-use",
  "usage.metric.usage_monthly": "Usage (monthly)",
  "usage.unit.available": "available",
  "usage.unit.credits": "credits",
  "usage.value.disabled": "Disabled",
  "usage.value.cap": "{0} cap",
  "usage.value.unlimited": "♾️ Unlimited",
  "usage.note.binding": "binding",
  "usage.note.binding_severity": "binding · {0}",
  "usage.note.busiest_model": "busiest of {0} model",
  "usage.note.busiest_models": "busiest of {0} models",
  "usage.note.used_limit_unit": "{0} / {1} {2}",
  "usage.note.bonus_codes": "{0} / {1} {2} · {3} codes",
  "usage.metric.agy_claude_others": "Claude & others",
  "usage.metric.agy_claude_others_session": "Claude & others (session)",
  "usage.metric.agy_claude_others_weekly": "Claude & others (weekly)",
  "usage.hint.statusline_now": "from {0}'s statusline, just now — no API call; plan and per-model limits need a CLI login",
  "usage.hint.statusline_minutes": "from {0}'s statusline, {1}m ago — no API call; plan and per-model limits need a CLI login",
  "usage.hint.claude_api_key": "API-key login has no subscription usage. Use `claude /login` or set CLAUDE_CODE_OAUTH_TOKEN (from `claude setup-token`).",
  "usage.hint.login_claude": "Log in with the Claude Code CLI (`claude`).",
  "usage.hint.login_agy": "Log in with the Antigravity CLI (`agy`).",
  "usage.hint.no_quota": "No quota information reported for this account.",
  "usage.hint.login_codex": "Log in with the Codex CLI (`codex`).",
  "usage.hint.codex_no_oauth": "auth.json has no OAuth login (API-key-only auth cannot read usage).",
  "usage.hint.login_grok": "Log in with the Grok CLI (`grok login`).",
  "usage.hint.grok_no_login": "auth.json has no usable login. Run `grok login`.",
  "usage.hint.login_kiro": "Log in with the Kiro CLI (`kiro-cli`).",
  "usage.hint.kiro_signed_out": "Signed out — run `kiro-cli` to log in.",
  "usage.hint.token_refreshing": "Token refreshing — try again in a moment.",
  "usage.hint.subscription_no_credit": "Subscription — no credit usage to report.",
  "usage.hint.no_quota_account": "No quota information available for this account type.",
  "usage.error.unreachable": "Could not reach {0}.",
  "usage.error.token_rejected": "Token rejected. Run `{0}` once to refresh the login.",
  "usage.error.rate_limited": "Rate limited by {0} — try again later.",
  "usage.error.rate_limited_transient": "{0}: can't fetch usage right now (rate limited). This does not affect your agents.",
  "usage.stale_rate_limited": "data from {0} min ago — can't refresh right now",
  "usage.error.http": "Usage request failed (HTTP {0}).",
  "usage.error.billing_http": "Billing request failed (HTTP {0}).",
  "usage.error.invalid_response": "Invalid response from usage endpoint.",
  "usage.error.invalid_billing_response": "Invalid response from billing endpoint.",
  "usage.error.invalid_kiro_response": "Invalid response from GetUsageLimits.",
  "usage.error.claude_token_expired": "Access token expired — it refreshes the next time any Claude instance runs.",
  "usage.error.codex_token_expired": "Access token expired. Run `codex` once to refresh it.",
  "usage.error.grok_expired": "Grok session expired. Run `grok login` again.",
  "usage.error.grok_response_changed": "Grok billing response changed.",
  "usage.error.agy_cap": "Individual cap reached — CLI is rate limited (resets in ~{0}). The per-model pool quotas are separate and may still read 0% used.",
  "usage.error.agy_no_refresh": "Access token expired and no refresh token is stored. Run `agy` once.",
  "usage.error.agy_token_expired": "Access token expired. Run `agy` once to refresh it (or set AGY_OAUTH_CLIENT_ID/SECRET to refresh automatically).",
  "usage.error.agy_login_expired": "Google sign-in expired. Run `agy` once to log in again.",
  "usage.error.agy_refresh_empty": "Google token refresh returned no token.",
  "usage.error.grok_auth_readonly": "Token expired and auth.json is read-only. Run `grok` once to refresh it.",
  "usage.error.grok_no_refresh": "Token expired and no refresh token was found. Run `grok login`.",
  "usage.error.grok_refresh_unreachable": "Could not reach auth.x.ai to refresh the token.",
  "usage.error.grok_invalid_refresh": "Invalid refresh response from auth.x.ai.",
  "usage.error.grok_persist": "Refreshed but could not write auth.json. Run `grok` once instead.",
  "usageButton": "Usage",
  "helpButton": "Help",
  "close": "Close",
  "expandProfile": "Show the profile",
  "rosterFailed": "Failed to load roster: {error}\n(Is the fleet running?)",
  "paneFailed": "⚠ Could not load pane for {name} (HTTP {status}).",
  "signInToSave": "Sign in to save — your session may have ended.",
  "avatarFailed": "Avatar upload failed: {error}",
  "saved": "Saved",
  "saveFailed": "Save failed: {error}",
  "signInToEdit": "Sign in to edit",
  "help4": "Drag groups or instances to reorder them in this browser.",
  "help6": "Press / to filter the list.",
  "title": "View",
  "notFound": "No instance called “{name}”",
  "notFoundHint": "It may have been deleted or renamed.",
  "noInstances": "No instances yet",
  "paneUnavailable": "This instance's terminal is not available (is it stopped?)",
  "rosterFailedShort": "The instance list could not be loaded.",
  "collapseGroup": "Fold {group}",
  "expandGroup": "Open {group}",
  "textSize": "Text size: {size}",
  "profileTitle": "Edit {name}'s profile",
  "avatar": "Avatar",
  "collapseProfile": "Hide the profile",
  "instancesLabel": "Instances"
 },
 "zh-TW": {
  "editProfile": "編輯個人資料",
  "save": "儲存",
  "cancel": "取消",
  "filterPh": "篩選：名稱、模型、後端",
  "filterClear": "清除篩選",
  "filterNone": "沒有符合的 instance",
  "filterShown": "顯示中",
  "filterStatus": "狀態",
  "filterCli": "CLI",
  "filterFacetsReset": "清除",
  "displayName": "顯示名稱",
  "role": "角色",
  "description": "描述",
  "saveHint": "儲存需要已登入的 session。請在 AgEnD bot 傳 /dashboard 取得登入碼。",
  "helpTitle": "📖 使用說明",
  "help1": "在清單裡選一個 instance：它的即時終端畫面會顯示在這裡。",
  "help2": "點群組名稱可以收合或展開。",
  "help3": "「編輯個人資料」可修改顯示名稱、角色、描述和頭像。",
  "help5": "「字級」會在剛好填滿 → 小 → 中 → 大之間切換。小、中、大是所有頁面共用的字級；剛好填滿讓終端畫面符合框的大小。",
  "densityFit": "剛好填滿",
  "densityComfortable": "舒適",
  "densityCompact": "精簡",
  "densityLabel": "字級密度",
  "usageTitle": "📊 AI 訂閱用量",
  "usageEmpty": "本機沒有偵測到已登入的 AI CLI。",
  "usageUpdated": "更新於",
  "usageRefresh": "重新整理",
  "usageHigh": "偏高",
  "usageNear": "接近上限",
  "usageMoveUp": "上移",
  "usageMoveDown": "下移",
  "tooltipBackend": "後端：{value}",
  "tooltipStatus": "狀態：{value}",
  "tooltipContext": "上下文：{value}",
  "tooltipModel": "模型：{value}",
  "tooltipEffort": "推理強度：{value}",
  "tooltipCost": "費用：{value}",
  "tooltipUnavailable": "無資料",
  "statusRunning": "運行中",
  "statusPaused": "已暫停",
  "statusStopped": "已停止",
  "statusCrashed": "已崩潰",
  "statusUnknown": "未知",
  "usageResets": "{t}後重置",
  "usageSoon": "即將重置",
  "usageFail": "無法載入用量資料。",
  "usage.title": "AI 訂閱用量",
  "usage.title_plain": "AI 訂閱用量",
  "usage.empty_active": "沒有使用中且支援用量追蹤的 Backend",
  "usage.not_logged_in": "未登入",
  "usage.error_fallback": "錯誤",
  "usage.no_data": "無資料",
  "usage.reset.in": "{0} 後重置",
  "usage.reset.soon": "即將重置",
  "usage.ticket_expiry": "🎫 最近過期：{0}（{1} 後）",
  "usage.duration.days_hours": "{0}d{1}h",
  "usage.duration.hours_minutes": "{0}h{1}m",
  "usage.duration.minutes": "{0}m",
  "usage.metric.session": "Session",
  "usage.metric.weekly": "每週",
  "usage.metric.monthly": "每月",
  "usage.metric.days_window": "{0} 天視窗",
  "usage.metric.named": "{0}",
  "usage.metric.named_session": "{0}（Session）",
  "usage.metric.named_weekly": "{0}（週）",
  "usage.metric.named_monthly": "{0}（每月）",
  "usage.metric.named_days": "{0}（{1} 天）",
  "usage.metric.extra_usage": "額外用量",
  "usage.metric.rate_limit_resets": "額度重置券",
  "usage.metric.credits": "額度",
  "usage.metric.weekly_limit": "每週上限",
  "usage.metric.pay_as_you_go": "隨用隨付",
  "usage.metric.bonus_credits": "贈送額度",
  "usage.metric.overage_charges": "超額費用",
  "usage.metric.pay_per_use": "隨用隨付",
  "usage.metric.usage_monthly": "用量（每月）",
  "usage.unit.available": "可用",
  "usage.unit.credits": "額度",
  "usage.value.disabled": "已停用",
  "usage.value.cap": "上限 {0}",
  "usage.value.unlimited": "♾️ 無限",
  "usage.note.binding": "生效",
  "usage.note.binding_severity": "生效 · {0}",
  "usage.note.busiest_model": "{0} 個模型中用量最高者",
  "usage.note.busiest_models": "{0} 個模型中用量最高者",
  "usage.note.used_limit_unit": "{0} / {1} {2}",
  "usage.note.bonus_codes": "{0} / {1} {2} · {3} 組代碼",
  "usage.metric.agy_claude_others": "Claude 與其他模型",
  "usage.metric.agy_claude_others_session": "Claude 與其他模型（Session）",
  "usage.metric.agy_claude_others_weekly": "Claude 與其他模型（每週）",
  "usage.hint.statusline_now": "來自 {0} 的 statusline（剛剛）；未呼叫 API，方案與各模型上限需要 CLI 登入資料",
  "usage.hint.statusline_minutes": "來自 {0} 的 statusline（{1} 分鐘前）；未呼叫 API，方案與各模型上限需要 CLI 登入資料",
  "usage.hint.claude_api_key": "API key 登入沒有訂閱用量資料。請使用 `claude /login`，或設定 CLAUDE_CODE_OAUTH_TOKEN（由 `claude setup-token` 取得）。",
  "usage.hint.login_claude": "請使用 Claude Code CLI（`claude`）登入。",
  "usage.hint.login_agy": "請使用 Antigravity CLI（`agy`）登入。",
  "usage.hint.no_quota": "此帳號未回報額度資訊。",
  "usage.hint.login_codex": "請使用 Codex CLI（`codex`）登入。",
  "usage.hint.codex_no_oauth": "auth.json 沒有 OAuth 登入資料；只有 API key 時無法讀取用量。",
  "usage.hint.login_grok": "請使用 Grok CLI（`grok login`）登入。",
  "usage.hint.grok_no_login": "auth.json 沒有可用的登入資料。請執行 `grok login`。",
  "usage.hint.login_kiro": "請使用 Kiro CLI（`kiro-cli`）登入。",
  "usage.hint.kiro_signed_out": "目前已登出；請執行 `kiro-cli` 登入。",
  "usage.hint.token_refreshing": "Token 更新中 — 請稍候再試。",
  "usage.hint.subscription_no_credit": "訂閱方案沒有可回報的額度用量。",
  "usage.hint.no_quota_account": "此帳號類型沒有可用的額度資訊。",
  "usage.error.unreachable": "無法連線至 {0}。",
  "usage.error.token_rejected": "Token 已被拒絕。請執行一次 `{0}` 以更新登入。",
  "usage.error.rate_limited": "{0} 暫時限制請求速率，請稍後再試。",
  "usage.error.rate_limited_transient": "暫時查不到 {0} 用量（{0} 限制查詢頻率），不影響你的 agent。",
  "usage.stale_rate_limited": "{0} 分鐘前的資料，暫時無法更新",
  "usage.error.http": "用量請求失敗（HTTP {0}）。",
  "usage.error.billing_http": "計費請求失敗（HTTP {0}）。",
  "usage.error.invalid_response": "用量端點回傳了無效資料。",
  "usage.error.invalid_billing_response": "計費端點回傳了無效資料。",
  "usage.error.invalid_kiro_response": "GetUsageLimits 回傳了無效資料。",
  "usage.error.claude_token_expired": "Access token 已過期；下次啟動任一 Claude instance 時會重新整理。",
  "usage.error.codex_token_expired": "Access token 已過期。請執行一次 `codex` 以重新整理。",
  "usage.error.grok_expired": "Grok session 已過期。請再次執行 `grok login`。",
  "usage.error.grok_response_changed": "Grok 計費回應格式已變更。",
  "usage.error.agy_cap": "個人上限已用完，CLI 正受到速率限制（約 {0} 後重置）。各模型的額度池是另一組計數，因此仍可能顯示 0% 已使用。",
  "usage.error.agy_no_refresh": "Access token 已過期，且未儲存 refresh token。請執行一次 `agy`。",
  "usage.error.agy_token_expired": "Access token 已過期。請執行一次 `agy` 重新整理，或設定 AGY_OAUTH_CLIENT_ID/SECRET 以自動更新。",
  "usage.error.agy_login_expired": "Google 登入已過期。請執行一次 `agy` 重新登入。",
  "usage.error.agy_refresh_empty": "Google token 更新回應沒有 access token。",
  "usage.error.grok_auth_readonly": "Token 已過期且 auth.json 為唯讀。請執行一次 `grok` 重新整理。",
  "usage.error.grok_no_refresh": "Token 已過期且找不到 refresh token。請執行 `grok login`。",
  "usage.error.grok_refresh_unreachable": "無法連線至 auth.x.ai 以更新 token。",
  "usage.error.grok_invalid_refresh": "auth.x.ai 回傳了無效的 token 更新資料。",
  "usage.error.grok_persist": "Token 已更新但無法寫入 auth.json。請改為執行一次 `grok`。",
  "usageButton": "用量",
  "helpButton": "說明",
  "close": "關閉",
  "expandProfile": "顯示個人資料",
  "rosterFailed": "載入 instance 清單失敗：{error}\n（Fleet 是否正在執行？）",
  "paneFailed": "⚠ 無法載入 {name} 的 pane（HTTP {status}）。",
  "signInToSave": "請先登入才能儲存：你的 session 可能已結束。",
  "avatarFailed": "上傳頭像失敗：{error}",
  "saved": "已儲存",
  "saveFailed": "儲存失敗：{error}",
  "signInToEdit": "登入後才能編輯",
  "help4": "拖曳群組或 instance 可調整這個瀏覽器的顯示順序。",
  "help6": "按 / 可以篩選清單。",
  "title": "檢視",
  "notFound": "沒有叫「{name}」的 instance",
  "notFoundHint": "它可能已被刪除或改名。",
  "noInstances": "還沒有 instance",
  "paneUnavailable": "無法取得這個 instance 的終端畫面（它是否已停止？）",
  "rosterFailedShort": "無法載入 instance 清單。",
  "collapseGroup": "收合 {group}",
  "expandGroup": "展開 {group}",
  "textSize": "字級：{size}",
  "profileTitle": "編輯 {name} 的個人資料",
  "avatar": "頭像",
  "collapseProfile": "隱藏個人資料",
  "instancesLabel": "Instances"
 }
});
