import { Cron } from "croner";
import type { DailySummaryConfig } from "./types.js";

export type TipLevel = "beginner" | "intermediate" | "advanced";

/**
 * Usage tips surfaced to users, graded by experience level.
 *
 * Any command, tool, or config key named here is verified against the command
 * registry, outbound tool schemas, and `types.ts` rather than written from
 * memory. When a capability is backend-specific (`/btw` is Claude Code only),
 * the tip says so rather than implying it works everywhere.
 *
 * The Chinese text is written natively, not translated from the English — the
 * two convey the same fact, and neither reads as a translation of the other.
 */
export interface Tip {
  id: string;
  level: TipLevel;
  text_en: string;
  text_zh: string;
}

export const TIPS: Tip[] = [
  // ── Beginner (30) ─────────────────────────────────────────────────────
  { id: "tip-001", level: "beginner",
    text_en: "An instance is one CLI process running in a tmux pane. Telegram presents it as a topic; Discord uses a channel or thread.",
    text_zh: "Instance 是在 tmux pane 中執行的一個 CLI process。Telegram 以 topic 呈現，Discord 則使用 channel 或 thread。" },
  { id: "tip-002", level: "beginner",
    text_en: "General is the fleet coordinator. It can route a request to an existing instance or create one when a separate session is needed.",
    text_zh: "General 是 fleet 的協調者，可將需求交給既有 instance，或在需要獨立 session 時建立新的 instance。" },
  { id: "tip-003", level: "beginner",
    text_en: "While an agent is working a Cancel button sits under its bubble — tap it to stop the current turn.",
    text_zh: "Agent 工作時，訊息下方會顯示取消按鈕；按下後會停止目前這一輪。" },
  { id: "tip-004", level: "beginner",
    text_en: "When tool_progress is enabled, a completed turn keeps its tool-history text after the Cancel button is removed.",
    text_zh: "啟用 tool_progress 後，一輪完成時會移除取消按鈕，但保留工具歷程文字。" },
  { id: "tip-005", level: "beginner",
    text_en: "`/ctx` reports the available context estimate, backend, model, and instance name. Some backends may not expose a context percentage.",
    text_zh: "`/ctx` 會顯示可取得的 context 估計值、backend、model 與 instance 名稱；部分 backend 可能無法提供百分比。" },
  { id: "tip-006", level: "beginner",
    text_en: "`/clear` asks a supported backend to reset its conversation context. It is admin-only and requires confirmation.",
    text_zh: "`/clear` 會要求支援的 backend 重設對話 context；此指令限管理員使用，並需要再次確認。" },
  { id: "tip-007", level: "beginner",
    text_en: "`/compact` sends the backend's context-reduction command. Backend semantics differ; Antigravity maps this action to a full clear.",
    text_zh: "`/compact` 會送出 backend 對應的 context 縮減指令；各 backend 語義不同，Antigravity 會改用完整清除。" },
  { id: "tip-008", level: "beginner",
    text_en: "`/usage` shows available subscription metrics for backends used by running or paused instances. Data may be unavailable when a CLI is not logged in or its provider exposes no metric.",
    text_zh: "`/usage` 顯示 running 或 paused instance 所使用 backend 的可用訂閱資料；CLI 未登入或 provider 未提供資料時可能顯示無資料。" },
  { id: "tip-009", level: "beginner",
    text_en: "`/model` opens the model selector or applies a model override. It uses the effective instance configuration and is admin-only.",
    text_zh: "`/model` 可開啟模型選單或套用 model override；它以 instance 的 effective config 為準，且限管理員使用。" },
  { id: "tip-010", level: "beginner",
    text_en: "`/status` summarizes fleet and instance state, including running, paused, stopped, and crashed processes.",
    text_zh: "`/status` 會整理 fleet 與 instance 狀態，包括 running、paused、stopped 與 crashed。" },
  { id: "tip-011", level: "beginner",
    text_en: "`/restart` requests a restart of the entire fleet, not only the current instance. Use an instance-specific restart action when only one CLI process should restart.",
    text_zh: "`/restart` 會要求重啟整個 fleet，不是只重啟目前的 instance；僅需重啟單一 CLI process 時，應使用 instance 專用的 restart 操作。" },
  { id: "tip-012", level: "beginner",
    text_en: "`/pause` applies only to an idle non-General instance. It stops the CLI process while preserving the data needed for a later wake.",
    text_zh: "`/pause` 只適用於 idle 且非 General 的 instance；它會停止 CLI process，並保留之後喚醒所需的資料。" },
  { id: "tip-013", level: "beginner",
    text_en: "A message to a paused instance starts its wake path automatically. `/wake` is available when an immediate manual wake is preferred.",
    text_zh: "訊息送到 paused instance 時會自動進入喚醒流程；需要立即手動喚醒時可使用 `/wake`。" },
  { id: "tip-014", level: "beginner",
    text_en: "`/cancel` stops the running turn from the keyboard — same effect as the Cancel button.",
    text_zh: "`/cancel` 可從文字指令停止目前這一輪，效果與取消按鈕相同。" },
  { id: "tip-015", level: "beginner",
    text_en: "`/effort` changes reasoning effort. Available levels depend on the backend and model; xhigh or max appear only when supported.",
    text_zh: "`/effort` 用於調整推理強度；可選等級取決於 backend 與 model，xhigh 或 max 只會在支援時提供。" },
  { id: "tip-016", level: "beginner",
    text_en: "`/update` installs the selected AgEnD release and restarts the fleet. Its progress message reports the current stage and elapsed time.",
    text_zh: "`/update` 會安裝所選的 AgEnD 版本並重啟 fleet；進度訊息會顯示目前階段與經過時間。" },
  { id: "tip-017", level: "beginner",
    text_en: "`/doctor` runs backend diagnostics from General. The `agend doctor` CLI additionally checks service, D-Bus, fleet, tmux, and IPC state.",
    text_zh: "General 中的 `/doctor` 會執行 backend 診斷；`agend doctor` CLI 另會檢查 service、D-Bus、fleet、tmux 與 IPC 狀態。" },
  { id: "tip-018", level: "beginner",
    text_en: "`/dashboard` returns links for View, editable View, Settings, and the Web UI. Token-bearing links are restricted to administrators.",
    text_zh: "`/dashboard` 會回傳 View、可編輯 View、Settings 與 Web UI 連結；含 token 的連結只提供給管理員。" },
  { id: "tip-019", level: "beginner",
    text_en: "Photos and files attached to a message are downloaded into AgEnD's inbox and delivered to the instance with a local path.",
    text_zh: "訊息附帶的圖片與檔案會下載到 AgEnD inbox，再以本機路徑投遞給 instance。" },
  { id: "tip-020", level: "beginner",
    text_en: "Telegram voice messages are delivered as audio. When Groq transcription is configured, AgEnD also prepends the transcript.",
    text_zh: "Telegram 語音訊息會以音訊投遞；若已設定 Groq 語音轉錄，AgEnD 也會在訊息前附上逐字稿。" },
  { id: "tip-021", level: "beginner",
    text_en: "Replying to a message gives the agent its quoted text as context. On supported Discord replies, referenced images are delivered as well.",
    text_zh: "回覆某則訊息時，agent 會收到被引用的文字；在支援的 Discord reply 中，被引用的圖片也會一併投遞。" },
  { id: "tip-022", level: "beginner",
    text_en: "AgEnD uses reactions as delivery status: ⏳ queued, 👀 delivered to the instance, ✅ turn confirmed, and ❌ failed.",
    text_zh: "AgEnD 以 reaction 表示投遞狀態：⏳ 排隊中、👀 已送到 instance、✅ 回合已確認、❌ 失敗。" },
  { id: "tip-023", level: "beginner",
    text_en: "Messages sent while an agent is busy may wait in its delivery queue. A delayed reply alone does not mean the message was lost; Cancel also discards deliveries that were queued before it.",
    text_zh: "Agent 忙碌時收到的訊息可能會先進入投遞佇列；回覆延遲本身不代表訊息遺失。按下取消時，也會丟棄先前尚未投遞的佇列內容。" },
  { id: "tip-024", level: "beginner",
    text_en: "Model-name matching in AgEnD is advisory. A safely formed name is passed to the CLI, which remains the authority and may reject an unavailable model.",
    text_zh: "AgEnD 對 model 名稱的相容性判斷只提供提示；格式安全的名稱仍會交給 CLI，是否可用由 CLI 最終決定。" },
  { id: "tip-025", level: "beginner",
    text_en: "General can make a best-effort model lookup before an override is chosen. Some CLIs expose no catalog, so an empty result does not prove that no models are available.",
    text_zh: "選擇 model override 前，可請 General 嘗試查詢模型清單；部分 CLI 不提供 catalog，因此空結果不代表沒有可用模型。" },
  { id: "tip-026", level: "beginner",
    text_en: "When shared backend credentials expire, AgEnD deduplicates the alert and requests a pause for the affected instance. After re-authentication, a new message or wake can resume it.",
    text_zh: "共用 backend 憑證過期時，AgEnD 會合併重複通知，並要求暫停受影響的 instance；重新登入後，可用新訊息或喚醒操作恢復。" },
  { id: "tip-027", level: "beginner",
    text_en: "When an instance does not set `model`, it inherits the fleet default or leaves selection to the CLI. Kiro's explicit `auto` mode is a separate dynamic-selection option.",
    text_zh: "Instance 未設定 `model` 時，會繼承 fleet default，或交由 CLI 選擇；Kiro 明確設定的 `auto` 則是另一種動態選擇模式。" },
  { id: "tip-028", level: "beginner",
    text_en: "`/sysinfo` prints host and version details that are useful when reporting an environment-specific problem.",
    text_zh: "`/sysinfo` 會顯示主機與版本資訊，適合附在與執行環境相關的問題回報中。" },
  { id: "tip-029", level: "beginner",
    text_en: "Telegram presents fleet conversations as topics, while Discord uses channels or threads. A Telegram command suffix such as `/ctx@botname` selects the bot, not an instance name.",
    text_zh: "Telegram 以 topic 呈現 fleet 對話，Discord 則使用 channel 或 thread；Telegram 的 `/ctx@botname` 後綴是在指定 bot，不是 instance 名稱。" },
  { id: "tip-030", level: "beginner",
    text_en: "Separate instances can work in parallel with independent conversation contexts. If they share a working directory, coordinate file edits to avoid conflicts.",
    text_zh: "不同 instance 可用獨立的對話 context 平行工作；若共用 working directory，仍需協調檔案修改以避免衝突。" },

  // ── Intermediate (40) ─────────────────────────────────────────────────
  { id: "tip-031", level: "intermediate",
    text_en: "`/steer <message>` can redirect an in-progress turn on Claude Code, Codex, and Grok. Other backends report that steering is unsupported.",
    text_zh: "`/steer <訊息>` 可在 Claude Code、Codex 與 Grok 的工作途中調整方向；其他 backend 會回報不支援 steering。" },
  { id: "tip-032", level: "intermediate",
    text_en: "Steering is pasted immediately when the supported TUI accepts busy input. If that cannot be confirmed, AgEnD can fall back to normal idle delivery instead of silently dropping the message.",
    text_zh: "支援的 TUI 可接受 busy input 時，steering 會立即貼入；若無法確認，AgEnD 可退回一般的 idle 投遞，而不是靜默丟棄。" },
  { id: "tip-033", level: "intermediate",
    text_en: "`/btw <message>` sends a labelled side question to Claude Code without asking it to abandon the current task. Other backends report it as unsupported.",
    text_zh: "`/btw <訊息>` 會向 Claude Code 投遞標記過的附帶問題，並要求不要放棄目前任務；其他 backend 會回報不支援。" },
  { id: "tip-034", level: "intermediate",
    text_en: "`/raw` is an admin-only escape hatch that forwards text without the usual message wrapper. It is intended for cases where the wrapper would change the desired CLI input.",
    text_zh: "`/raw` 是限管理員使用的直接投遞方式，會省略一般訊息 wrapper；適合 wrapper 會改變預期 CLI 輸入的情況。" },
  { id: "tip-035", level: "intermediate",
    text_en: "General can delegate independent parts of a request to different instances and combine their results in the original conversation.",
    text_zh: "General 可將需求中的獨立部分交給不同 instance，再把結果整合回原本的對話。" },
  { id: "tip-036", level: "intermediate",
    text_en: "Instances can exchange focused questions and results, but they do not automatically share conversation history or assume access to one another's workspace.",
    text_zh: "Instance 之間可交換具體問題與結果，但不會自動共用對話歷程，也不應假設能存取彼此的 workspace。" },
  { id: "tip-037", level: "intermediate",
    text_en: "For work with independent steps, ask General to coordinate several instances in parallel and return one consolidated answer.",
    text_zh: "需求包含多個互不相依的步驟時，可請 General 協調多個 instance 平行處理，再回傳一份整合結果。" },
  { id: "tip-038", level: "intermediate",
    text_en: "Descriptions and tags help General distinguish instances with similar names and route work by responsibility or capability.",
    text_zh: "Description 與 tags 可協助 General 區分名稱相近的 instance，並依責任或能力安排工作。" },
  { id: "tip-039", level: "intermediate",
    text_en: "Cross-instance delivery may be queued while the target is busy. A sender-side timeout does not prove non-delivery, so avoid resending solely because of that timeout.",
    text_zh: "目標忙碌時，跨 instance 訊息可能先排隊；發送端 timeout 不代表沒有投遞，因此不應只因 timeout 就重送。" },
  { id: "tip-040", level: "intermediate",
    text_en: "A General-managed team can send one coordinated request to a selected group of instances. Narrow groups reduce unnecessary wake-ups and duplicate work.",
    text_zh: "General 管理的 team 可把同一需求交給選定的一組 instance；縮小群組範圍可減少不必要的喚醒與重複工作。" },
  { id: "tip-041", level: "intermediate",
    text_en: "Before creating an instance, General can inspect the existing fleet and reuse a suitable one. A separate instance is most useful when an independent session or workspace is required.",
    text_zh: "建立 instance 前，General 可先檢視既有 fleet 並重用合適的 instance；需要獨立 session 或 workspace 時，再建立新的較合適。" },
  { id: "tip-042", level: "intermediate",
    text_en: "When General creates an instance without a working directory, AgEnD creates a workspace under `~/.agend/workspaces/<name>`.",
    text_zh: "General 建立 instance 時若未指定 working directory，AgEnD 會在 `~/.agend/workspaces/<name>` 建立 workspace。" },
  { id: "tip-043", level: "intermediate",
    text_en: "`~/.agend/fleet.yaml` is the fleet configuration source of truth. Changes applied through Settings are saved there and then reloaded.",
    text_zh: "`~/.agend/fleet.yaml` 是 fleet 設定的來源；透過 Settings 套用的變更會寫入此檔案並重新載入。" },
  { id: "tip-044", level: "intermediate",
    text_en: "After editing fleet.yaml by hand, run `agend validate` or ask General to validate the configuration before restarting the fleet.",
    text_zh: "手動修改 fleet.yaml 後，可執行 `agend validate`，或請 General 在重啟 fleet 前檢查設定。" },
  { id: "tip-045", level: "intermediate",
    text_en: "A schedule is either recurring (`cron`) or one-shot (`at` with an ISO timestamp). Ask General to use one form, not both, for the same schedule.",
    text_zh: "排程可選週期性的 `cron`，或使用 ISO 時間的單次 `at`；同一排程只應使用其中一種。" },
  { id: "tip-046", level: "intermediate",
    text_en: "A silent schedule sends its trigger directly to the target instance without posting the trigger text to the conversation. The agent may still reply if the task asks it to.",
    text_zh: "靜默排程會把觸發內容直接送到目標 instance，不在對話中張貼觸發文字；若任務要求回覆，agent 仍可能發出結果。" },
  { id: "tip-047", level: "intermediate",
    text_en: "Schedules default to Asia/Taipei. Set an IANA `timezone` when the intended schedule uses another time zone.",
    text_zh: "排程預設使用 Asia/Taipei；若預期時間屬於其他時區，應設定對應的 IANA `timezone`。" },
  { id: "tip-048", level: "intermediate",
    text_en: "Schedules can target a specific instance, allowing General to place recurring or one-shot work with the instance responsible for it.",
    text_zh: "排程可指定特定 instance，讓 General 把週期或單次工作交給對應的負責者。" },
  { id: "tip-049", level: "intermediate",
    text_en: "General can list, edit, disable, or delete existing schedules. Disabling preserves a schedule for later reactivation without firing it.",
    text_zh: "General 可列出、修改、停用或刪除既有排程；停用會保留設定供日後恢復，但期間不會觸發。" },
  { id: "tip-050", level: "intermediate",
    text_en: "`/tips` shows another available tip. Administrators can use `/tips off` or `/tips on` to change daily delivery; dismissing a tip prevents that item from returning.",
    text_zh: "`/tips` 可立即顯示另一則可用提示；管理員可用 `/tips off` 或 `/tips on` 調整每日投遞。將某則標記為已知後，它不會再次出現。" },
  { id: "tip-051", level: "intermediate",
    text_en: "Teams provide reusable groups of instances for recurring collaboration patterns, such as implementation plus review.",
    text_zh: "Teams 可保存經常一起合作的 instance 組合，例如實作與 review 的固定搭配。" },
  { id: "tip-052", level: "intermediate",
    text_en: "Shared decisions let instances reuse an agreed architectural choice after restarts instead of independently rediscovering it.",
    text_zh: "Shared decisions 可讓不同 instance 在重啟後沿用已確認的架構選擇，不必各自重新推導。" },
  { id: "tip-053", level: "intermediate",
    text_en: "Collaboration messages exchange selected information; they do not merge the participants' full conversation histories or session memories.",
    text_zh: "協作訊息只交換選定資訊，不會合併參與 instance 的完整對話歷程或 session memory。" },
  { id: "tip-054", level: "intermediate",
    text_en: "A fleet restart preserves fleet.yaml and instance data. Whether a CLI resumes the same conversation session depends on that backend's resume support.",
    text_zh: "Fleet restart 會保留 fleet.yaml 與 instance 資料；CLI 是否續接同一個對話 session，則取決於 backend 的 resume 支援。" },
  { id: "tip-055", level: "intermediate",
    text_en: "The View page shows the live tmux pane for an instance and is useful when a prompt, installer, or TUI state needs visual inspection.",
    text_zh: "View 頁面會顯示 instance 的即時 tmux pane，適合檢查互動提示、安裝流程或 TUI 狀態。" },
  { id: "tip-056", level: "intermediate",
    text_en: "`agend ls` provides a terminal summary of running, idle, paused, stopped, and crashed instances, including available context estimates.",
    text_zh: "`agend ls` 會在終端整理 running、idle、paused、stopped 與 crashed instance，並顯示可取得的 context 估計值。" },
  { id: "tip-057", level: "intermediate",
    text_en: "`tool_progress` controls the tool list under a working bubble: \"standard\" for semantic labels, \"verbose\" to add command previews, \"off\" (the default) for none.",
    text_zh: "`tool_progress` 控制工作泡泡下的工具清單：`standard` 顯示語意標籤、`verbose` 再加上指令預覽、`off`（預設）則完全不顯示。" },
  { id: "tip-058", level: "intermediate",
    text_en: "`defaults.progress_min_elapsed` controls how long before the bubble starts showing elapsed time — raise it if short turns feel noisy.",
    text_zh: "`defaults.progress_min_elapsed` 決定泡泡多久後才開始顯示已耗時。短任務覺得吵就調高。" },
  { id: "tip-059", level: "intermediate",
    text_en: "`agend export-chat --from 09:00 --to 18:00 -o day.html` exports fleet activity to an HTML archive. Review it for sensitive content before sharing.",
    text_zh: "`agend export-chat --from 09:00 --to 18:00 -o day.html` 可將 fleet 活動匯出為 HTML archive；分享前應先檢查敏感內容。" },
  { id: "tip-060", level: "intermediate",
    text_en: "Run `/save <name>` in an instance conversation. Kiro receives `/chat save <name>` and Claude Code receives `/export <name>.md`; other backends return an unsupported message.",
    text_zh: "在 instance 對話中執行 `/save <名稱>`；Kiro 會收到 `/chat save <名稱>`，Claude Code 會收到 `/export <名稱>.md`，其他 backend 則回覆不支援。" },
  { id: "tip-061", level: "intermediate",
    text_en: "`auto_pause_after` is disabled by default (`0`). Enable or adjust it in Settings; it is a hot change that takes effect without restarting the instance.",
    text_zh: "`auto_pause_after` 預設為停用（`0`）；可在 Settings 啟用或調整，屬於 hot change，不需重啟 instance 即可生效。" },
  { id: "tip-062", level: "intermediate",
    text_en: "`tool_set` limits the MCP tools exposed to an instance. Change it in the instance's Settings editor; applying this cold change restarts that instance.",
    text_zh: "`tool_set` 可限制 instance 可見的 MCP tools；可在該 instance 的 Settings 編輯，套用此 cold change 時會重啟該 instance。" },
  { id: "tip-063", level: "intermediate",
    text_en: "Run `/effort` in the instance conversation to view or change reasoning effort. The result states whether the change applied at runtime or required an instance restart.",
    text_zh: "在 instance 對話中執行 `/effort` 可查看或調整推理強度；結果會說明變更是 runtime 生效，或需要重啟 instance。" },
  { id: "tip-064", level: "intermediate",
    text_en: "An instance backend can be changed through Settings or fleet.yaml. This is a cold configuration change that restarts the instance, and conversation continuity across different CLIs is not guaranteed.",
    text_zh: "可透過 Settings 或 fleet.yaml 變更 instance backend；這屬於 cold config，會重啟 instance，而且不同 CLI 之間不保證延續對話。" },
  { id: "tip-065", level: "intermediate",
    text_en: "Set an instance's display name, description, and tags in Settings. These hot fields update routing context and labels without restarting the instance.",
    text_zh: "可在 Settings 設定 instance 的 display name、description 與 tags；這些 hot fields 會更新 routing context 與標示，不需重啟 instance。" },
  { id: "tip-066", level: "intermediate",
    text_en: "Ask General to replace an instance when a new process is needed. Without a new workspace it is similar to restart: configuration and location remain, and backend resume support determines session continuity.",
    text_zh: "需要新的 process 時可請 General replace instance；若沒有建立新 workspace，行為與 restart 類似：設定與位置保留，session 是否延續由 backend 的 resume 支援決定。" },
  { id: "tip-067", level: "intermediate",
    text_en: "Use the Settings page to review a change's impact before applying it. Hot fields apply immediately; cold fields such as backend or working directory restart the affected instance.",
    text_zh: "可在 Settings 套用前查看變更影響；hot fields 會即時生效，backend 或 working directory 等 cold fields 則會重啟受影響的 instance。" },
  { id: "tip-068", level: "intermediate",
    text_en: "Instance settings inherit fleet defaults unless overridden. Edit defaults in Settings, or edit `defaults` in fleet.yaml when a field has no dedicated control.",
    text_zh: "Instance 設定在未 override 時會繼承 fleet defaults；可在 Settings 修改 defaults，沒有專用控制項的欄位則修改 fleet.yaml 的 `defaults`。" },
  { id: "tip-069", level: "intermediate",
    text_en: "In a multi-adapter fleet, choose an instance's Channel binding in Settings (or set `channel_id` in fleet.yaml). Applying the cold change restarts the instance on the selected persona.",
    text_zh: "多 adapter fleet 可在 Settings 選擇 instance 的 Channel binding（或在 fleet.yaml 設定 `channel_id`）；套用此 cold change 會重啟 instance 並綁定所選 persona。" },
  { id: "tip-070", level: "intermediate",
    text_en: "ClassicBot treats ordinary messages as an ongoing conversation. In a shared collaboration channel, mention the intended bot; manage ClassicBot channels and defaults from Settings.",
    text_zh: "ClassicBot 會把一般訊息視為持續對話；在多人協作頻道中應 mention 預期的 bot，ClassicBot channels 與 defaults 可在 Settings 管理。" },

  // ── Advanced (30) ─────────────────────────────────────────────────────
  { id: "tip-071", level: "advanced",
    text_en: "Set `backend_options.codex.provider` in fleet.yaml to select a custom provider. This cold change restarts the instance; provider definition and credentials remain in Codex's own config and environment.",
    text_zh: "在 fleet.yaml 設定 `backend_options.codex.provider` 可選擇 custom provider；此 cold change 會重啟 instance，provider 定義與憑證仍放在 Codex 自己的 config 與 environment。" },
  { id: "tip-072", level: "advanced",
    text_en: "Ask General to look up models for the specific custom-provider Codex instance. Instance-scoped lookup reads its isolated CODEX_HOME and can differ from the account-wide catalog.",
    text_zh: "可請 General 查詢特定 custom-provider Codex instance 的 models；instance-scoped lookup 會讀取其隔離的 CODEX_HOME，結果可能不同於帳號層級 catalog。" },
  { id: "tip-073", level: "advanced",
    text_en: "When General returns a model lookup, check whether its scope is `instance` or `global`. A global fallback may not describe a custom provider accurately.",
    text_zh: "General 回傳 model lookup 後，應確認 scope 是 `instance` 或 `global`；global fallback 未必能準確描述 custom provider。" },
  { id: "tip-074", level: "advanced",
    text_en: "Define reusable instance groups under `templates` in fleet.yaml, then ask General to deploy the selected template.",
    text_zh: "先在 fleet.yaml 的 `templates` 定義可重用的 instance 組合，再請 General 部署所選 template。" },
  { id: "tip-075", level: "advanced",
    text_en: "Ask General to deploy a template with a branch when each instance should receive its own git worktree for parallel work.",
    text_zh: "需要每個 instance 取得獨立 git worktree 進行平行工作時，可請 General 以 branch 部署 template。" },
  { id: "tip-076", level: "advanced",
    text_en: "Ask General to inspect a template deployment or tear down its tracked instance group when the deployment is no longer needed.",
    text_zh: "需要檢視 template deployment，或在不再使用時移除其 tracked instance group，可請 General 操作。" },
  { id: "tip-077", level: "advanced",
    text_en: "Ask General to inspect an instance when its workspace origin is unclear. Managed worktrees expose their source repository as `worktree_source`.",
    text_zh: "不確定 instance 的 workspace 來源時，可請 General 檢視；managed worktree 會以 `worktree_source` 顯示來源 repository。" },
  { id: "tip-078", level: "advanced",
    text_en: "Ask General for a repository checkout when read-only inspection is needed. It creates a detached worktree, not a write lock or exclusivity guarantee.",
    text_zh: "需要唯讀檢查 repository 時可請 General checkout；它會建立 detached worktree，不是 write lock，也不保證獨占。" },
  { id: "tip-079", level: "advanced",
    text_en: "Set `defaults.warm_cap` through Settings' advanced YAML editor or fleet.yaml. It is hot-reloaded; over the cap, the least-recently-active idle instance is auto-paused.",
    text_zh: "可透過 Settings 的 advanced YAML editor 或 fleet.yaml 設定 `defaults.warm_cap`；它會 hot-reload，超過上限時最久未活動的 idle instance 會自動暫停。" },
  { id: "tip-080", level: "advanced",
    text_en: "Use Settings to tune time-based `auto_pause_after`; use its advanced YAML editor or fleet.yaml for count-based `warm_cap`. Both are hot settings and can be combined.",
    text_zh: "可在 Settings 調整依時間判斷的 `auto_pause_after`，並透過 advanced YAML editor 或 fleet.yaml 設定依數量判斷的 `warm_cap`；兩者皆為 hot settings，可搭配使用。" },
  { id: "tip-081", level: "advanced",
    text_en: "Configure `warm_cap` in Settings' advanced YAML editor or fleet.yaml. Its eviction excludes General instances, preserving coordinator availability.",
    text_zh: "可在 Settings 的 advanced YAML editor 或 fleet.yaml 設定 `warm_cap`；eviction 會排除 General instance，以保留協調者可用性。" },
  { id: "tip-082", level: "advanced",
    text_en: "Configure `context_guardian` in fleet.yaml; it is a cold instance setting. It monitors context but does not clear or recycle the CLI session, so backend-native compaction remains separate.",
    text_zh: "`context_guardian` 需在 fleet.yaml 設定，屬於 cold instance setting；它只監控 context，不會清除或回收 CLI session，backend 原生 compaction 仍是另一套機制。" },
  { id: "tip-083", level: "advanced",
    text_en: "Change `log_level` in Settings. It hot-reloads daemon logging without restarting the instance; use debug or trace only while the additional detail is needed.",
    text_zh: "可在 Settings 調整 `log_level`；它會 hot-reload daemon logging，不需重啟 instance，debug 或 trace 適合只在需要額外細節時使用。" },
  { id: "tip-084", level: "advanced",
    text_en: "Tune `hang_detector` in Settings' Detection section or fleet.yaml. It is a cold change; long silent tasks can resemble a hang, so choose `timeout_minutes` from observed workloads.",
    text_zh: "可在 Settings 的 Detection section 或 fleet.yaml 調整 `hang_detector`；這是 cold change，長時間無輸出的任務可能類似 hang，因此應依實際 workload 設定 `timeout_minutes`。" },
  { id: "tip-085", level: "advanced",
    text_en: "Edit `restart_policy` in fleet.yaml, then reload the config; this cold change restarts affected instances. Tune retry count, backoff, and reset timing for the selected CLI.",
    text_zh: "在 fleet.yaml 修改 `restart_policy` 後重新載入設定；此 cold change 會重啟受影響的 instance。Retry 次數、backoff 與 reset timing 應配合所選 CLI。" },
  { id: "tip-086", level: "advanced",
    text_en: "Set `model_failover` in the instance's Settings editor or fleet.yaml. Applying this cold change restarts the instance; compatible five-hour usage telemetry controls later rotation.",
    text_zh: "可在 instance 的 Settings editor 或 fleet.yaml 設定 `model_failover`；套用此 cold change 會重啟 instance，後續 rotation 由相容的五小時用量 telemetry 控制。" },
  { id: "tip-087", level: "advanced",
    text_en: "Configure `defaults.cost_guard` in fleet.yaml and restart the fleet for full effect. It can stop an instance at the fleet limit only when the backend supplies usable cost telemetry.",
    text_zh: "在 fleet.yaml 設定 `defaults.cost_guard` 後需重啟 fleet 才能完整生效；只有 backend 提供可用 cost telemetry 時，它才能在 fleet 上限停止 instance。" },
  { id: "tip-088", level: "advanced",
    text_en: "Set `pre_task_command` in fleet.yaml; changing it restarts the instance. Commands such as `/chat load ...` are Kiro-specific, so verify the selected CLI's syntax first.",
    text_zh: "`pre_task_command` 需在 fleet.yaml 設定，變更時會重啟 instance；`/chat load ...` 等指令只適用 Kiro，應先確認所選 CLI 的語法。" },
  { id: "tip-089", level: "advanced",
    text_en: "Set `kiro_ui` through Settings' advanced YAML editor or fleet.yaml. Changing `legacy`, `tui`, or `v3` restarts the instance, and pane-scraped signals can differ by mode.",
    text_zh: "可透過 Settings 的 advanced YAML editor 或 fleet.yaml 設定 `kiro_ui`；變更 `legacy`、`tui` 或 `v3` 會重啟 instance，pane-scraped signals 也可能隨模式不同。" },
  { id: "tip-090", level: "advanced",
    text_en: "Set `terminal.columns` and `terminal.rows` through Settings' advanced YAML editor or fleet.yaml. The cold change restarts the instance; larger dimensions show more content but can shrink View text.",
    text_zh: "可透過 Settings 的 advanced YAML editor 或 fleet.yaml 設定 `terminal.columns` 與 `terminal.rows`；此 cold change 會重啟 instance，較大尺寸能顯示更多內容，但可能縮小 View 字體。" },
  { id: "tip-091", level: "advanced",
    text_en: "Choose `agent_mode: cli` in Settings' Advanced section when a supported backend should use agend-agent HTTP instead of native MCP. Applying it restarts the instance.",
    text_zh: "需要讓支援的 backend 改用 agend-agent HTTP 而非原生 MCP 時，可在 Settings 的 Advanced section 選擇 `agent_mode: cli`；套用後會重啟 instance。" },
  { id: "tip-092", level: "advanced",
    text_en: "If an MCP tool connection stays unavailable, ask General to restart the affected instance. AgEnD cannot directly replace the CLI-owned stdio child mid-session.",
    text_zh: "MCP tool connection 持續無法使用時，可請 General 重啟受影響的 instance；AgEnD 無法在 session 中途直接替換由 CLI 掌握的 stdio child。" },
  { id: "tip-093", level: "advanced",
    text_en: "Enable `mcp_proxy_reply` through Settings' advanced YAML editor or fleet.yaml only when pane text is safe to relay. It is hot-reloaded and remains off by default.",
    text_zh: "只有在 pane text 適合轉送時，才透過 Settings 的 advanced YAML editor 或 fleet.yaml 啟用 `mcp_proxy_reply`；它可 hot-reload，且預設為關閉。" },
  { id: "tip-094", level: "advanced",
    text_en: "For a `general_topic` instance, leave Tool set inherited in Settings so AgEnD assigns the internal `general` profile. An explicit `standard` override omits coordinator tools and can make dispatch fail silently.",
    text_zh: "對 `general_topic` instance，應在 Settings 讓 Tool set 保持繼承，由 AgEnD 自動配置內部 `general` profile；若明確 override 為 `standard`，會缺少協調工具，分派可能靜默失敗。" },
  { id: "tip-095", level: "advanced",
    text_en: "Manage `allowed_users` in Settings' Advanced & Access section, or edit channel access in fleet.yaml. Channel access changes require a fleet restart; an empty locked allowlist has no admin.",
    text_zh: "可在 Settings 的 Advanced & Access section 管理 `allowed_users`，或修改 fleet.yaml 的 channel access；變更後需重啟 fleet，locked allowlist 為空時不會有管理員。" },
  { id: "tip-096", level: "advanced",
    text_en: "Adjust `startup.concurrency` and `stagger_delay_ms` in Settings' Startup section or fleet.yaml. They take effect on the next fleet start.",
    text_zh: "可在 Settings 的 Startup section 或 fleet.yaml 調整 `startup.concurrency` 與 `stagger_delay_ms`；設定會在下一次 fleet start 生效。" },
  { id: "tip-097", level: "advanced",
    text_en: "Add tags such as `code-reviewer` or `researcher` in the instance's Settings editor. Tags hot-reload into General's routing context without restarting the instance.",
    text_zh: "可在 instance 的 Settings editor 加入 `code-reviewer`、`researcher` 等 tags；tags 會 hot-reload 到 General 的 routing context，不需重啟 instance。" },
  { id: "tip-098", level: "advanced",
    text_en: "Set fleet-level `project_roots` through Settings' advanced YAML editor or fleet.yaml. After reload, General can create instances only under those real-path boundaries.",
    text_zh: "可透過 Settings 的 advanced YAML editor 或 fleet.yaml 設定 fleet-level `project_roots`；重新載入後，General 只能在這些 real-path boundaries 下建立 instance。" },
  { id: "tip-099", level: "advanced",
    text_en: "Enable `lightweight` in the instance's Settings editor only when transcript, context, approval, and prompt monitors are unnecessary. Applying this cold change restarts the instance.",
    text_zh: "只有在不需要 transcript、context、approval 與 prompt monitors 時，才於 instance 的 Settings editor 啟用 `lightweight`；套用此 cold change 會重啟 instance。" },
  { id: "tip-100", level: "advanced",
    text_en: "Configure `mcp_auto_restart` in fleet.yaml; it defaults to enabled and changing it restarts the instance. Recovery normally waits for idle, with a bounded stale fallback.",
    text_zh: "`mcp_auto_restart` 需在 fleet.yaml 設定，預設啟用，變更時會重啟 instance；recovery 通常等待 idle，並有 bounded stale fallback。" },
];

export function visibleTipLevels(dismissedIds: ReadonlySet<string>): ReadonlySet<TipLevel> {
  const counts = { beginner: 0, intermediate: 0 };
  const totals = { beginner: 0, intermediate: 0 };
  for (const tip of TIPS) {
    if (tip.level === "beginner" || tip.level === "intermediate") {
      totals[tip.level]++;
      if (dismissedIds.has(tip.id)) counts[tip.level]++;
    }
  }
  const advancedUnlocked = counts.beginner > totals.beginner / 2
    && counts.intermediate > totals.intermediate / 2;
  return new Set<TipLevel>(advancedUnlocked
    ? ["beginner", "intermediate", "advanced"]
    : ["beginner", "intermediate"]);
}

export function selectTip(
  dismissedIds: ReadonlySet<string>,
  random: () => number = Math.random,
): Tip | null {
  const levels = visibleTipLevels(dismissedIds);
  const candidates = TIPS.filter(tip => levels.has(tip.level) && !dismissedIds.has(tip.id));
  if (candidates.length === 0) return null;
  const index = Math.min(candidates.length - 1, Math.max(0, Math.floor(random() * candidates.length)));
  return candidates[index];
}

/** Fleet-internal daily trigger. It is intentionally not persisted in fleet.yaml. */
export class DailyTipScheduler {
  private job: Cron | null = null;

  constructor(
    private readonly config: DailySummaryConfig,
    private readonly timezone: string,
    private readonly onTip: () => void | Promise<void>,
  ) {}

  start(): void {
    const cron = `${this.config.minute} ${this.config.hour} * * *`;
    this.job = new Cron(cron, { timezone: this.timezone }, () => {
      Promise.resolve(this.onTip()).catch(() => { /* caller owns logging */ });
    });
  }

  stop(): void {
    this.job?.stop();
    this.job = null;
  }
}
